# Generated by run_anchor_audit.py. Do not edit: rerunning overwrites this file.
# To overrule a verdict, add an entry to data/fontanchors_audit/overrides.py.
#
# italic: 273 anchors audited; 85 bad, 29 suspect, 159 ok
# anchor class 0 = above, 2 = below

audit = {
    "B": {  # U+0042 B
        0: {  # above
            "xy": (447, 850),
            "verdict": "suspect",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks -41 from this anchor (1 glyph(s) compared)',
            ],
        },
    },
    "D": {  # U+0044 D
        0: {  # above
            "xy": (396, 850),
            "verdict": "suspect",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +71 from this anchor (2 glyph(s) compared)',
            ],
        },
    },
    "E": {  # U+0045 E
        2: {  # below
            "xy": (269, -107),
            "verdict": "suspect",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks -38 from this anchor (3 glyph(s) compared)',
            ],
        },
    },
    "P": {  # U+0050 P
        2: {  # below
            "xy": (140, -110),
            "verdict": "suspect",
            "reasons": [
                'suspect [style-position] anchor sits 34% across the glyph; 49% in the other styles',
            ],
        },
    },
    "d": {  # U+0064 d
        0: {  # above
            "xy": (218, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -182 from the centre line (42% of the width)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 3 of 3 tested marks fit there",
                'suspect [precomposed] precomposed glyphs centre marks +79 from this anchor (1 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +129 from that style's; -182 off centre here (-52 there)",
            ],
        },
    },
    "f": {  # U+0066 f
        2: {  # below
            "xy": (222, -111),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "bad [aspect] glyph sits on aspect 'd' but y = -111 is the reference of an inner aspect, 127 inside the bottom of the glyph; 0 of 2 tested marks fit there",
            ],
        },
    },
    "g": {  # U+0067 g
        2: {  # below
            "xy": (197, -319),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: dot below 31 from the glyph (normally 54)',
            ],
        },
    },
    "h": {  # U+0068 h
        0: {  # above
            "xy": (409, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 1 of 3 tested marks fit there",
            ],
        },
    },
    "k": {  # U+006B k
        0: {  # above
            "xy": (405, 646),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 646 is the reference of an inner aspect, 52 inside the top of the glyph; 1 of 3 tested marks fit there",
            ],
        },
    },
    "p": {  # U+0070 p
        0: {  # above
            "xy": (411, 646),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron 49 from the glyph (normally 102), circumflex 19 from the glyph (normally 70)',
            ],
        },
        2: {  # below
            "xy": (248, -110),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "suspect [aspect] glyph sits on aspect 'd' but y = -110 is the reference of an inner aspect, 128 inside the bottom of the glyph; 1 of 2 tested marks fit there",
                "suspect [copy] same anchor as R (U+0052), a different letterform; +39 from this glyph's centre line",
                'suspect [style-position] anchor sits 59% across the glyph; 43% in the other styles',
            ],
        },
    },
    "q": {  # U+0071 q
        2: {  # below
            "xy": (169, -110),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron below 39 from the glyph (normally 79)',
                "suspect [aspect] glyph sits on aspect 'd' but y = -110 is the reference of an inner aspect, 128 inside the bottom of the glyph; 1 of 2 tested marks fit there",
            ],
        },
    },
    "w": {  # U+0077 w
        0: {  # above
            "xy": (348, 646),
            "verdict": "suspect",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +97 from this anchor (4 glyph(s) compared)',
            ],
        },
    },
    "y": {  # U+0079 y
        2: {  # below
            "xy": (368, -107),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is +150 from the centre line (33% of the width)',
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "bad [aspect] glyph sits on aspect 'd' but y = -107 is the reference of an inner aspect, 127 inside the bottom of the glyph; 0 of 2 tested marks fit there",
            ],
        },
    },
    "AE": {  # U+00C6 Æ
        2: {  # below
            "xy": (549, -107),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -49 from that style's; +172 off centre here (+122 there)",
            ],
        },
    },
    "oslash": {  # U+00F8 ø
        2: {  # below
            "xy": (186, -107),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron below 36 from the glyph (normally 79)',
                "suspect [copy] same anchor as o (U+006F) and 16 other(s), a different letterform; -16 from this glyph's centre line",
            ],
        },
    },
    "thorn": {  # U+00FE þ
        0: {  # above
            "xy": (278, 646),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 646 is the reference of an inner aspect, 52 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +141 from that style's; -100 off centre here (+42 there)",
            ],
        },
    },
    "Eng": {  # U+014A Ŋ
        0: {  # above
            "xy": (346, 804),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 804 is 46 from every reference value although the glyph sits on aspect 'c'",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +145 from that style's; -115 off centre here (+30 there)",
            ],
        },
        2: {  # below
            "xy": (364, -109),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
            ],
        },
    },
    "eng": {  # U+014B ŋ
        0: {  # above
            "xy": (264, 646),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +128 from that style's; -104 off centre here (+24 there)",
            ],
        },
        2: {  # below
            "xy": (265, -111),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "bad [aspect] glyph sits on aspect 'd' but y = -111 is the reference of an inner aspect, 122 inside the bottom of the glyph; 0 of 2 tested marks fit there",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -32 from that style's; +58 off centre here (+25 there)",
            ],
        },
    },
    "uni0181": {  # U+0181 Ɓ
        0: {  # above
            "xy": (327, 805),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 805 is 45 from every reference value although the glyph sits on aspect 'c'",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +153 from that style's; -129 off centre here (+24 there)",
            ],
        },
        2: {  # below
            "xy": (328, -108),
            "verdict": "bad",
            "reasons": [
                "suspect [copy] same anchor as N (U+004E), a different letterform; +66 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -41 from that style's; +66 off centre here (+25 there)",
            ],
        },
    },
    "uni0184": {  # U+0184 Ƅ
        0: {  # above
            "xy": (267, 805),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -168 from the centre line (34% of the width)',
                "bad [reference] y = 805 is 45 from every reference value although the glyph sits on aspect 'c'",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +158 from that style's; -168 off centre here (-10 there)",
            ],
        },
        2: {  # below
            "xy": (268, -108),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -36 from that style's; +27 off centre here (-10 there)",
            ],
        },
    },
    "uni0185": {  # U+0185 ƅ
        2: {  # below
            "xy": (238, -108),
            "verdict": "bad",
            "reasons": [
                "suspect [copy] same anchor as B (U+0042), a different letterform; +50 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -39 from that style's; +50 off centre here (+12 there)",
            ],
        },
    },
    "uni018A": {  # U+018A Ɗ
        0: {  # above
            "xy": (306, 805),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 805 is 45 from every reference value although the glyph sits on aspect 'c'",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +149 from that style's; -211 off centre here (-62 there)",
            ],
        },
        2: {  # below
            "xy": (369, -107),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -45 from that style's; +46 off centre here (+0 there)",
            ],
        },
    },
    "uni018C": {  # U+018C ƌ
        0: {  # above
            "xy": (209, 650),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -177 from the centre line (42% of the width)',
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 650 is the reference of an inner aspect, 48 inside the top of the glyph; 0 of 3 tested marks fit there",
            ],
        },
    },
    "uni0194": {  # U+0194 Ɣ
        0: {  # above
            "xy": (331, 805),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 805 is 45 from every reference value although the glyph sits on aspect 'c'",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +121 from that style's; -98 off centre here (+22 there)",
            ],
        },
    },
    "uni0195": {  # U+0195 ƕ
        0: {  # above
            "xy": (299, 645),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +114 from that style's; -159 off centre here (-44 there)",
            ],
        },
    },
    "uni0199": {  # U+0199 ƙ
        2: {  # below
            "xy": (263, -107),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -38 from that style's; +39 off centre here (+1 there)",
            ],
        },
    },
    "uni019C": {  # U+019C Ɯ
        0: {  # above
            "xy": (431, 801),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 801 is 49 from every reference value although the glyph sits on aspect 'c'",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +156 from that style's; -159 off centre here (-2 there)",
            ],
        },
        2: {  # below
            "xy": (450, -108),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -37 from that style's; +54 off centre here (+16 there)",
            ],
        },
    },
    "uni019E": {  # U+019E ƞ
        0: {  # above
            "xy": (264, 646),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as ŋ (U+014B) and 1 other(s), as is its other anchor, a different letterform; -88 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (265, -111),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [aspect] glyph sits on aspect 'd' but y = -111 is the reference of an inner aspect, 122 inside the bottom of the glyph; 0 of 2 tested marks fit there",
                "bad [copy] same anchor as ŋ (U+014B) and 1 other(s), as is its other anchor, a different letterform; +74 from this glyph's centre line",
            ],
        },
    },
    "uni01A2": {  # U+01A2 Ƣ
        0: {  # above
            "xy": (355, 804),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -267 from the centre line (31% of the width)',
                "bad [reference] y = 804 is 46 from every reference value although the glyph sits on aspect 'c'",
            ],
        },
    },
    "uni01B4": {  # U+01B4 ƴ
        0: {  # above
            "xy": (270, 644),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +127 from that style's; -173 off centre here (-46 there)",
            ],
        },
    },
    "uni01DD": {  # U+01DD ǝ
        0: {  # above
            "xy": (302, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [turned] turned form of e (U+0065); anchor x is -79 from the transformed anchor of that letter',
            ],
        },
    },
    "oslashacute": {  # U+01FF ǿ
        2: {  # below
            "xy": (186, -107),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron below 36 from the glyph (normally 79)',
                "suspect [copy] same anchor as o (U+006F) and 16 other(s), a different letterform; -16 from this glyph's centre line",
            ],
        },
    },
    "uni0235": {  # U+0235 ȵ
        0: {  # above
            "xy": (261, 646),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -191 from the centre line (32% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +119 from that style's; -191 off centre here (-72 there)",
            ],
        },
        2: {  # below
            "xy": (262, -111),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
            ],
        },
    },
    "uni0236": {  # U+0236 ȶ
        2: {  # below
            "xy": (163, -109),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
            ],
        },
    },
    "uni0239": {  # U+0239 ȹ
        0: {  # above
            "xy": (377, 646),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +141 from that style's; -138 off centre here (+4 there)",
            ],
        },
    },
    "uni0247": {  # U+0247 ɇ
        0: {  # above
            "xy": (332, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: dot 37 from the glyph (normally 80)',
            ],
        },
        2: {  # below
            "xy": (158, -108),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] crowded: dot below 24 from the glyph (normally 54)',
                "bad [copy] same anchor as e (U+0065), as is its other anchor, a different letterform; -27 from this glyph's centre line",
            ],
        },
    },
    "uni024D": {  # U+024D ɍ
        0: {  # above
            "xy": (312, 646),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [copy] same anchor as r (U+0072), as is its other anchor, a different letterform; -123 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (113, -110),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "bad [copy] same anchor as r (U+0072), as is its other anchor, a different letterform; -161 from this glyph's centre line",
            ],
        },
    },
    "uni0250": {  # U+0250 ɐ
        2: {  # below
            "xy": (229, -114),
            "verdict": "bad",
            "reasons": [
                "suspect [copy] same anchor as h (U+0068) and 1 other(s), a different letterform; +29 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -17 from that style's; +29 off centre here (+12 there)",
            ],
        },
    },
    "uni0253": {  # U+0253 ɓ
        2: {  # below
            "xy": (212, -114),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as ɑ (U+0251) and 8 other(s), a different letterform; -22 from this glyph's centre line",
            ],
        },
    },
    "uni0254": {  # U+0254 ɔ
        0: {  # above
            "xy": (322, 654),
            "verdict": "suspect",
            "reasons": [
                "suspect [reference] y = 654 is 9 from the nearest reference value (aspect 'x')",
            ],
        },
    },
    "uni0255": {  # U+0255 ɕ
        2: {  # below
            "xy": (212, -114),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron below 12 from the glyph (normally 79)',
                "suspect [copy] same anchor as ɑ (U+0251) and 8 other(s), a different letterform; +18 from this glyph's centre line",
            ],
        },
    },
    "uni0256": {  # U+0256 ɖ
        0: {  # above
            "xy": (218, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -228 from the centre line (42% of the width)',
                "bad [copy] same anchor as d (U+0064) and 2 other(s), a different letterform; -228 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +132 from that style's; -228 off centre here (-96 there)",
            ],
        },
        2: {  # below
            "xy": (212, -114),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "bad [copy] same anchor as ɑ (U+0251) and 8 other(s), a different letterform; -73 from this glyph's centre line",
            ],
        },
    },
    "uni0257": {  # U+0257 ɗ
        0: {  # above
            "xy": (218, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -232 from the centre line (44% of the width)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 3 of 3 tested marks fit there",
                "bad [copy] same anchor as d (U+0064) and 2 other(s), a different letterform; -232 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +128 from that style's; -232 off centre here (-104 there)",
            ],
        },
        2: {  # below
            "xy": (212, -114),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as ɑ (U+0251) and 8 other(s), a different letterform; -77 from this glyph's centre line",
            ],
        },
    },
    "uni0258": {  # U+0258 ɘ
        0: {  # above
            "xy": (204, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -155 from the centre line (48% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +138 from that style's; -155 off centre here (-16 there)",
            ],
        },
    },
    "uni025A": {  # U+025A ɚ
        2: {  # below
            "xy": (212, -114),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as ɑ (U+0251) and 8 other(s), a different letterform; -77 from this glyph's centre line",
            ],
        },
    },
    "uni025B": {  # U+025B ɛ
        0: {  # above
            "xy": (322, 654),
            "verdict": "suspect",
            "reasons": [
                "suspect [reference] y = 654 is 9 from the nearest reference value (aspect 'x')",
                "suspect [copy] same anchor as ɔ (U+0254), a different letterform; -20 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (212, -114),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as ɑ (U+0251) and 8 other(s), a different letterform; +34 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -23 from that style's; +34 off centre here (+10 there)",
            ],
        },
    },
    "uni025D": {  # U+025D ɝ
        2: {  # below
            "xy": (212, -114),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as ɑ (U+0251) and 8 other(s), a different letterform; -24 from this glyph's centre line",
            ],
        },
    },
    "uni025E": {  # U+025E ɞ
        2: {  # below
            "xy": (256, -114),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -27 from that style's; +42 off centre here (+14 there)",
            ],
        },
    },
    "uni0262": {  # U+0262 ɢ
        0: {  # above
            "xy": (265, 645),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +128 from that style's; -121 off centre here (+6 there)",
            ],
        },
    },
    "uni0265": {  # U+0265 ɥ
        0: {  # above
            "xy": (258, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [turned] turned form of h (U+0068); anchor x is -157 from the transformed anchor of that letter',
            ],
        },
        2: {  # below
            "xy": (219, -129),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "suspect [reference] y = -129 is 19 from the nearest reference value (aspect 'd')",
            ],
        },
    },
    "uni0266": {  # U+0266 ɦ
        0: {  # above
            "xy": (299, 565),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [reference] y = 565 is 80 from every reference value although the glyph sits on aspect 'a'",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +156 from that style's; -119 off centre here (+36 there)",
            ],
        },
    },
    "uni0269": {  # U+0269 ɩ
        0: {  # above
            "xy": (123, 645),
            "verdict": "bad",
            "reasons": [
                'bad [extent] anchor x is 84 outside the glyph, to the left',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +127 from that style's; -174 off centre here (-47 there)",
            ],
        },
    },
    "uni026A": {  # U+026A ɪ
        0: {  # above
            "xy": (128, 645),
            "verdict": "bad",
            "reasons": [
                'bad [extent] anchor x is 38 outside the glyph, to the left',
                'suspect [style-position] anchor sits -17% across the glyph; 48% in the other styles',
            ],
        },
        2: {  # below
            "xy": (139, -114),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -20 from that style's; +23 off centre here (+2 there)",
            ],
        },
    },
    "uni026B": {  # U+026B ɫ
        2: {  # below
            "xy": (146, -114),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -26 from that style's; +28 off centre here (+2 there)",
            ],
        },
    },
    "uni026C": {  # U+026C ɬ
        2: {  # below
            "xy": (218, -120),
            "verdict": "bad",
            "reasons": [
                "suspect [reference] y = -120 is 10 from the nearest reference value (aspect 'b')",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -30 from that style's; +66 off centre here (+36 there)",
            ],
        },
    },
    "uni026F": {  # U+026F ɯ
        0: {  # above
            "xy": (407, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [turned] turned form of m (U+006D); anchor x is -112 from the transformed anchor of that letter',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +130 from that style's; -114 off centre here (+16 there)",
                'suspect [style-position] anchor sits 34% across the glyph; 53% in the other styles',
            ],
        },
        2: {  # below
            "xy": (410, -114),
            "verdict": "bad",
            "reasons": [
                'suspect [turned] turned form of m (U+006D); anchor x is +33 from the transformed anchor of that letter',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -32 from that style's; +51 off centre here (+19 there)",
            ],
        },
    },
    "uni0270": {  # U+0270 ɰ
        2: {  # below
            "xy": (294, -114),
            "verdict": "suspect",
            "reasons": [
                "suspect [aspect] glyph sits on aspect 'd' but y = -114 is the reference of an inner aspect, 118 inside the bottom of the glyph; 2 of 2 tested marks fit there",
            ],
        },
    },
    "uni0271": {  # U+0271 ɱ
        0: {  # above
            "xy": (383, 645),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +124 from that style's; -106 off centre here (+18 there)",
            ],
        },
        2: {  # below
            "xy": (383, -105),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] crowded: dot below 30 from the glyph (normally 54), macron below 43 from the glyph (normally 79)',
                "bad [aspect] glyph sits on aspect 'd' but y = -105 is the reference of an inner aspect, 124 inside the bottom of the glyph; 0 of 2 tested marks fit there",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -36 from that style's; +53 off centre here (+18 there)",
            ],
        },
    },
    "uni0272": {  # U+0272 ɲ
        0: {  # above
            "xy": (264, 646),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as ŋ (U+014B) and 1 other(s), as is its other anchor, a different letterform; -98 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +128 from that style's; -98 off centre here (+30 there)",
            ],
        },
        2: {  # below
            "xy": (265, -111),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] crowded: macron below 18 from the glyph (normally 79)',
                "suspect [aspect] glyph sits on aspect 'd' but y = -111 is the reference of an inner aspect, 118 inside the bottom of the glyph; 1 of 2 tested marks fit there",
                "bad [copy] same anchor as ŋ (U+014B) and 1 other(s), as is its other anchor, a different letterform; +64 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -33 from that style's; +64 off centre here (+30 there)",
            ],
        },
    },
    "uni0273": {  # U+0273 ɳ
        0: {  # above
            "xy": (263, 645),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +121 from that style's; -153 off centre here (-32 there)",
            ],
        },
        2: {  # below
            "xy": (262, -112),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [aspect] glyph sits on aspect 'd' but y = -112 is the reference of an inner aspect, 117 inside the bottom of the glyph; 0 of 2 tested marks fit there",
            ],
        },
    },
    "uni0279": {  # U+0279 ɹ
        2: {  # below
            "xy": (190, -114),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is +128 from the centre line (38% of the width)',
                'suspect [turned] turned form of r (U+0072); anchor x is +123 from the transformed anchor of that letter',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -116 from that style's; +128 off centre here (+13 there)",
            ],
        },
    },
    "uni027A": {  # U+027A ɺ
        2: {  # below
            "xy": (203, -114),
            "verdict": "suspect",
            "reasons": [
                'suspect [turned] turned form of ɼ (U+027C); anchor x is -94 from the transformed anchor of that letter',
            ],
        },
    },
    "uni027C": {  # U+027C ɼ
        0: {  # above
            "xy": (222, 703),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -123 from the centre line (34% of the width)',
                "suspect [reference] y = 703 is 41 from both the reference values and the clearance rule (aspect 'x+19')",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +158 from that style's; -123 off centre here (+36 there)",
            ],
        },
    },
    "uni028A": {  # U+028A ʊ
        2: {  # below
            "xy": (258, -114),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -18 from that style's; +23 off centre here (+4 there)",
            ],
        },
    },
    "uni028B": {  # U+028B ʋ
        0: {  # above
            "xy": (259, 645),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +150 from that style's; -126 off centre here (+24 there)",
            ],
        },
    },
    "uni028F": {  # U+028F ʏ
        2: {  # below
            "xy": (239, -107),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -16 from that style's; +19 off centre here (+4 there)",
            ],
        },
    },
    "uni0295": {  # U+0295 ʕ
        2: {  # below
            "xy": (230, -107),
            "verdict": "bad",
            "reasons": [
                "suspect [copy] same anchor as ƃ (U+0183), a different letterform; +51 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -42 from that style's; +51 off centre here (+9 there)",
            ],
        },
    },
    "uni029E": {  # U+029E ʞ
        0: {  # above
            "xy": (255, 646),
            "verdict": "suspect",
            "reasons": [
                'suspect [centre] anchor x is -173 from the centre line (37% of the width)',
                'suspect [turned] turned form of k (U+006B); anchor x is -169 from the transformed anchor of that letter',
                'suspect [style-position] anchor sits 13% across the glyph; 34% in the other styles',
            ],
        },
        2: {  # below
            "xy": (183, -107),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron below 47 from the glyph (normally 79)',
                "suspect [aspect] glyph sits on aspect 'd' but y = -107 is the reference of an inner aspect, 131 inside the bottom of the glyph; 1 of 2 tested marks fit there",
                'suspect [turned] turned form of k (U+006B); anchor x is -59 from the transformed anchor of that letter',
            ],
        },
    },
    "uni02A0": {  # U+02A0 ʠ
        0: {  # above
            "xy": (238, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -231 from the centre line (39% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +149 from that style's; -231 off centre here (-82 there)",
            ],
        },
    },
    "uni02AE": {  # U+02AE ʮ
        0: {  # above
            "xy": (278, -214),
            "verdict": "bad",
            "reasons": [
                'bad [side] above anchor at y = -214, in the lower half of the glyph or below it',
                'suspect [collision] crowded: macron 57 from the glyph (normally 102)',
                'bad [reference] y = -214 is 859 from every reference value',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -38 from that style's; +28 off centre here (-10 there)",
            ],
        },
        2: {  # below
            "xy": (318, 542),
            "verdict": "bad",
            "reasons": [
                'bad [side] below anchor at y = 542, in the upper half of the glyph or above it',
                'bad [reference] y = 542 is 652 from every reference value',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +122 from that style's; -92 off centre here (+30 there)",
            ],
        },
    },
    "uni02AF": {  # U+02AF ʯ
        0: {  # above
            "xy": (278, -214),
            "verdict": "bad",
            "reasons": [
                'bad [side] above anchor at y = -214, in the lower half of the glyph or below it',
                'bad [reference] y = -214 is 859 from every reference value',
            ],
        },
        2: {  # below
            "xy": (318, 542),
            "verdict": "bad",
            "reasons": [
                'bad [side] below anchor at y = 542, in the upper half of the glyph or above it',
                'bad [reference] y = 542 is 652 from every reference value',
                "bad [copy] same anchor as ʮ (U+02AE), as is its other anchor, a different letterform; -128 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +118 from that style's; -128 off centre here (-10 there)",
            ],
        },
    },
    "beta": {  # U+03B2 β
        2: {  # below
            "xy": (275, -114),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] crowded: macron below 47 from the glyph (normally 79)',
                "suspect [aspect] glyph sits on aspect 'd' but y = -114 is the reference of an inner aspect, 121 inside the bottom of the glyph; 1 of 2 tested marks fit there",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -47 from that style's; +61 off centre here (+14 there)",
            ],
        },
    },
    "upsilon": {  # U+03C5 υ
        0: {  # above
            "xy": (259, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +102 from this anchor (1 glyph(s) compared)',
                "suspect [copy] same anchor as ʋ (U+028B), a different letterform; -95 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +119 from that style's; -95 off centre here (+24 there)",
            ],
        },
    },
    "uni040B": {  # U+040B Ћ
        0: {  # above
            "xy": (300, 802),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -232 from the centre line (32% of the width)',
                'suspect [collision] circumflex overlaps the glyph (1 of 3 marks tested)',
                "suspect [reference] y = 802 is 48 from both the reference values and the clearance rule (aspect 'a-25')",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +158 from that style's; -232 off centre here (-74 there)",
            ],
        },
        2: {  # below
            "xy": (436, -111),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -36 from that style's; +98 off centre here (+62 there)",
            ],
        },
    },
    "uni0473": {  # U+0473 ѳ
        0: {  # above
            "xy": (224, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -139 from the centre line (39% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +135 from that style's; -139 off centre here (-4 there)",
                'suspect [style-position] anchor sits 11% across the glyph; 49% in the other styles',
            ],
        },
        2: {  # below
            "xy": (234, -107),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -25 from that style's; +31 off centre here (+6 there)",
            ],
        },
    },
    "uni0475": {  # U+0475 ѵ
        0: {  # above
            "xy": (268, 646),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +150 from that style's; -147 off centre here (+3 there)",
            ],
        },
    },
    "uni04E9": {  # U+04E9 ө
        0: {  # above
            "xy": (236, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -126 from the centre line (34% of the width)',
                'suspect [precomposed] precomposed glyphs centre marks +127 from this anchor (1 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +110 from that style's; -126 off centre here (-16 there)",
                'suspect [style-position] anchor sits 16% across the glyph; 45% in the other styles',
            ],
        },
        2: {  # below
            "xy": (246, -107),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -50 from that style's; +44 off centre here (-6 there)",
            ],
        },
    },
    "uni1E72": {  # U+1E72 Ṳ
        0: {  # above
            "xy": (346, 850),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +155 from that style's; -140 off centre here (+15 there)",
            ],
        },
    },
    "uni1E73": {  # U+1E73 ṳ
        0: {  # above
            "xy": (255, 646),
            "verdict": "bad",
            "reasons": [
                "suspect [copy] same anchor as ʞ (U+029E), a different letterform; -148 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +132 from that style's; -148 off centre here (-16 there)",
            ],
        },
    },
    "uni2184": {  # U+2184 ↄ
        0: {  # above
            "xy": (180, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -156 from the centre line (43% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +135 from that style's; -156 off centre here (-22 there)",
            ],
        },
    },
    "uni2C68": {  # U+2C68 ⱨ
        0: {  # above
            "xy": (299, 645),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [copy] same anchor as ƕ (U+0195), as is its other anchor, a different letterform; -101 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +138 from that style's; -101 off centre here (+36 there)",
            ],
        },
        2: {  # below
            "xy": (259, -111),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as ƕ (U+0195), as is its other anchor, a different letterform; +19 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -23 from that style's; +19 off centre here (-4 there)",
            ],
        },
    },
    "uni2C69": {  # U+2C69 Ⱪ
        0: {  # above
            "xy": (336, 798),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 798 is 52 from every reference value although the glyph sits on aspect 'c'",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +184 from that style's; -174 off centre here (+10 there)",
            ],
        },
    },
    "uni2C6A": {  # U+2C6A ⱪ
        0: {  # above
            "xy": (275, 646),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 646 is the reference of an inner aspect, 52 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +151 from that style's; -135 off centre here (+16 there)",
            ],
        },
    },
    "uni2C6B": {  # U+2C6B Ⱬ
        0: {  # above
            "xy": (320, 803),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -175 from the centre line (30% of the width)',
                'suspect [collision] circumflex overlaps the glyph (1 of 3 marks tested)',
                "suspect [reference] y = 803 is 47 from both the reference values and the clearance rule (aspect 'c+22')",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +173 from that style's; -175 off centre here (-2 there)",
            ],
        },
    },
    "uni2C6C": {  # U+2C6C ⱬ
        0: {  # above
            "xy": (218, 646),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -132 from the centre line (37% of the width)',
                "bad [copy] same anchor as d (U+0064) and 2 other(s), a different letterform; -132 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +144 from that style's; -132 off centre here (+12 there)",
            ],
        },
        2: {  # below
            "xy": (204, -111),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron below 18 from the glyph (normally 79)',
                "suspect [copy] same anchor as S (U+0053), a different letterform; +15 from this glyph's centre line",
            ],
        },
    },
    "uni2C74": {  # U+2C74 ⱴ
        0: {  # above
            "xy": (252, 646),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -146 from the centre line (34% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +143 from that style's; -146 off centre here (-2 there)",
            ],
        },
    },
}
