# Human overrides of the anchor audit (data/fontanchors_audit/{style}.py).
#
# The audit files are regenerated by run_anchor_audit.py; this file is not.
# Stage 1 of the patch pipeline deletes an anchor if the audit says "bad",
# unless it is overruled here:
#
#     "keep"    never delete, whatever the audit says
#     "delete"  delete, even if the audit says "suspect" or lists nothing
#
# style -> glyph name -> anchor class (0 above, 2 below) -> "keep" | "delete"

overrides = {
    "regular": {
        # "q": {0: "keep"},
    },
    "italic": {
    },
    "semibold": {
    },
    "semibold_italic": {
    },
}
