# Generated by run_anchor_audit.py. Do not edit: rerunning overwrites this file.
# To overrule a verdict, add an entry to data/fontanchors_audit/overrides.py.
#
# regular: 487 anchors audited; 139 bad, 54 suspect, 294 ok
# anchor class 0 = above, 2 = below

audit = {
    "R": {  # U+0052 R
        2: {  # below
            "xy": (258, -110),
            "verdict": "suspect",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +35 from this anchor (2 glyph(s) compared)',
            ],
        },
    },
    "Z": {  # U+005A Z
        2: {  # below
            "xy": (287, -110),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as E (U+0045), a different letterform; -22 from this glyph's centre line",
            ],
        },
    },
    "d": {  # U+0064 d
        0: {  # above
            "xy": (218, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron overlaps the glyph (1 of 3 marks tested)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 1 of 3 tested marks fit there",
                'suspect [precomposed] precomposed glyphs centre marks -40 from this anchor (1 glyph(s) compared)',
            ],
        },
    },
    "h": {  # U+0068 h
        0: {  # above
            "xy": (299, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron overlaps the glyph (1 of 3 marks tested)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 1 of 3 tested marks fit there",
            ],
        },
    },
    "j": {  # U+006A j
        2: {  # below
            "xy": (109, -319),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as J (U+004A), a different letterform; +34 from this glyph's centre line",
            ],
        },
    },
    "k": {  # U+006B k
        0: {  # above
            "xy": (306, 784),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] crowded: macron 4 from the glyph (normally 105), circumflex 12 from the glyph (normally 72)',
                "bad [reference] y = 784 is 66 from every reference value although the glyph sits on aspect 'a'",
            ],
        },
        2: {  # below
            "xy": (290, -214),
            "verdict": "bad",
            "reasons": [
                'bad [reference] y = -214 is 104 from every reference value',
            ],
        },
    },
    "p": {  # U+0070 p
        2: {  # below
            "xy": (179, -319),
            "verdict": "suspect",
            "reasons": [
                'suspect [style-position] anchor sits 37% across the glyph; 54% in the other styles',
            ],
        },
    },
    "q": {  # U+0071 q
        0: {  # above
            "xy": (238, 645),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as o (U+006F) and 1 other(s), a different letterform; -30 from this glyph's centre line",
            ],
        },
    },
    "y": {  # U+0079 y
        2: {  # below
            "xy": (242, -319),
            "verdict": "suspect",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +124 from this anchor (1 glyph(s) compared)',
            ],
        },
    },
    "AE": {  # U+00C6 Æ
        0: {  # above
            "xy": (480, 850),
            "verdict": "suspect",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +78 from this anchor (1 glyph(s) compared)',
            ],
        },
    },
    "Thorn": {  # U+00DE Þ
        0: {  # above
            "xy": (281, 850),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as E (U+0045), a different letterform; +31 from this glyph's centre line",
            ],
        },
    },
    "ccedilla": {  # U+00E7 ç
        0: {  # above
            "xy": (255, 834),
            "verdict": "suspect",
            "reasons": [
                "suspect [reference] y = 834 is 16 from the nearest reference value (aspect 'x')",
            ],
        },
    },
    "thorn": {  # U+00FE þ
        0: {  # above
            "xy": (278, 646),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 646 is the reference of an inner aspect, 52 inside the top of the glyph; 1 of 3 tested marks fit there",
            ],
        },
    },
    "aogonek": {  # U+0105 ą
        2: {  # below
            "xy": (146, -108),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
            ],
        },
    },
    "Eogonek": {  # U+0118 Ę
        2: {  # below
            "xy": (279, -110),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
            ],
        },
    },
    "eogonek": {  # U+0119 ę
        2: {  # below
            "xy": (70, -108),
            "verdict": "suspect",
            "reasons": [
                'suspect [centre] anchor x is -152 from the centre line (41% of the width)',
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
            ],
        },
    },
    "kgreenlandic": {  # U+0138 ĸ
        2: {  # below
            "xy": (132, -108),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as f (U+0066), a different letterform; -135 from this glyph's centre line",
            ],
        },
    },
    "Eng": {  # U+014A Ŋ
        0: {  # above
            "xy": (346, 804),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 804 is 46 from every reference value although the glyph sits on aspect 'c'",
            ],
        },
        2: {  # below
            "xy": (353, -109),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
            ],
        },
    },
    "eng": {  # U+014B ŋ
        2: {  # below
            "xy": (265, -111),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [copy] same anchor as n (U+006E) and 1 other(s), as is its other anchor, a different letterform; +25 from this glyph's centre line",
            ],
        },
    },
    "Uogonek": {  # U+0172 Ų
        2: {  # below
            "xy": (188, -110),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
            ],
        },
    },
    "uni0181": {  # U+0181 Ɓ
        0: {  # above
            "xy": (327, 805),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 805 is 45 from every reference value although the glyph sits on aspect 'c'",
            ],
        },
        2: {  # below
            "xy": (328, -108),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as U (U+0055) and 1 other(s), a different letterform; +25 from this glyph's centre line",
            ],
        },
    },
    "uni0184": {  # U+0184 Ƅ
        0: {  # above
            "xy": (267, 805),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 805 is 45 from every reference value although the glyph sits on aspect 'c'",
            ],
        },
    },
    "uni018A": {  # U+018A Ɗ
        0: {  # above
            "xy": (306, 805),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 805 is 45 from every reference value although the glyph sits on aspect 'c'",
            ],
        },
    },
    "uni018C": {  # U+018C ƌ
        0: {  # above
            "xy": (214, 650),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 650 is the reference of an inner aspect, 48 inside the top of the glyph; 1 of 3 tested marks fit there",
            ],
        },
    },
    "uni0194": {  # U+0194 Ɣ
        0: {  # above
            "xy": (331, 805),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 805 is 45 from every reference value although the glyph sits on aspect 'c'",
            ],
        },
    },
    "uni0195": {  # U+0195 ƕ
        0: {  # above
            "xy": (299, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron 1 from the glyph (normally 105), circumflex 8 from the glyph (normally 72)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 1 of 3 tested marks fit there",
            ],
        },
    },
    "uni019C": {  # U+019C Ɯ
        0: {  # above
            "xy": (431, 801),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 801 is 49 from every reference value although the glyph sits on aspect 'c'",
            ],
        },
    },
    "uni019E": {  # U+019E ƞ
        2: {  # below
            "xy": (280, -111),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "bad [aspect] glyph sits on aspect 'd' but y = -111 is the reference of an inner aspect, 123 inside the bottom of the glyph; 0 of 2 tested marks fit there",
            ],
        },
    },
    "uni01A2": {  # U+01A2 Ƣ
        0: {  # above
            "xy": (359, 804),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 804 is 46 from every reference value although the glyph sits on aspect 'c'",
            ],
        },
    },
    "uni01A4": {  # U+01A4 Ƥ
        2: {  # below
            "xy": (363, -110),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as C (U+0043) and 1 other(s), a different letterform; +45 from this glyph's centre line",
            ],
        },
    },
    "uni0235": {  # U+0235 ȵ
        2: {  # below
            "xy": (262, -111),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron below 8 from the glyph (normally 78)',
                "suspect [copy] same anchor as L (U+004C) and 1 other(s), a different letterform; -71 from this glyph's centre line",
            ],
        },
    },
    "uni0236": {  # U+0236 ȶ
        2: {  # below
            "xy": (163, -109),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "suspect [copy] same anchor as t (U+0074) and 1 other(s), a different letterform; -33 from this glyph's centre line",
            ],
        },
    },
    "uni0237": {  # U+0237 ȷ
        0: {  # above
            "xy": (140, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [style-position] anchor sits 77% across the glyph; 51% in the other styles',
            ],
        },
    },
    "uni0238": {  # U+0238 ȸ
        2: {  # below
            "xy": (348, -109),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as N (U+004E), a different letterform; -26 from this glyph's centre line",
            ],
        },
    },
    "uni024A": {  # U+024A Ɋ
        0: {  # above
            "xy": (355, 804),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 804 is 46 from every reference value although the glyph sits on aspect 'c'",
            ],
        },
        2: {  # below
            "xy": (350, -113),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron below 19 from the glyph (normally 78)',
            ],
        },
    },
    "uni024B": {  # U+024B ɋ
        2: {  # below
            "xy": (212, -114),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron below 30 from the glyph (normally 78)',
            ],
        },
    },
    "uni0250": {  # U+0250 ɐ
        0: {  # above
            "xy": (228, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [turned] turned form of a (U+0061); anchor x is -38 from the transformed anchor of that letter',
            ],
        },
    },
    "uni0251": {  # U+0251 ɑ
        2: {  # below
            "xy": (212, -114),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as ɋ (U+024B) and 8 other(s), as is its other anchor, a different letterform; -60 from this glyph's centre line",
            ],
        },
    },
    "uni0252": {  # U+0252 ɒ
        0: {  # above
            "xy": (264, 645),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as n (U+006E) and 2 other(s), a different letterform; +17 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (259, -114),
            "verdict": "suspect",
            "reasons": [
                'suspect [turned] turned form of ɑ (U+0251); anchor x is -32 from the transformed anchor of that letter',
            ],
        },
    },
    "uni0253": {  # U+0253 ɓ
        0: {  # above
            "xy": (480, 630),
            "verdict": "bad",
            "reasons": [
                'bad [extent] anchor x is 24 outside the glyph, to the right',
                'suspect [collision] crowded: macron 23 from the glyph (normally 105)',
                "suspect [reference] y = 630 is 15 from the nearest reference value (aspect 'a')",
            ],
        },
        2: {  # below
            "xy": (212, -114),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as ɋ (U+024B) and 8 other(s), a different letterform; -53 from this glyph's centre line",
            ],
        },
    },
    "uni0255": {  # U+0255 ɕ
        2: {  # below
            "xy": (212, -114),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
            ],
        },
    },
    "uni0256": {  # U+0256 ɖ
        0: {  # above
            "xy": (218, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 1 of 3 tested marks fit there",
            ],
        },
        2: {  # below
            "xy": (212, -114),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] crowded: macron below 27 from the glyph (normally 78)',
                "bad [copy] same anchor as ɋ (U+024B) and 8 other(s), a different letterform; -102 from this glyph's centre line",
            ],
        },
    },
    "uni0257": {  # U+0257 ɗ
        0: {  # above
            "xy": (218, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] crowded: macron 9 from the glyph (normally 105), circumflex 4 from the glyph (normally 72)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 1 of 3 tested marks fit there",
                "bad [copy] same anchor as d (U+0064) and 3 other(s), a different letterform; -104 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (212, -114),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as ɋ (U+024B) and 8 other(s), a different letterform; -110 from this glyph's centre line",
            ],
        },
    },
    "uni025A": {  # U+025A ɚ
        2: {  # below
            "xy": (212, -114),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as ɋ (U+024B) and 8 other(s), a different letterform; -94 from this glyph's centre line",
            ],
        },
    },
    "uni025D": {  # U+025D ɝ
        0: {  # above
            "xy": (209, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "suspect [copy] same anchor as a (U+0061) and 60 other(s), a different letterform; -26 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (212, -114),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as ɋ (U+024B) and 8 other(s), a different letterform; -22 from this glyph's centre line",
            ],
        },
    },
    "uni025F": {  # U+025F ɟ
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 48 other(s), a different letterform; +72 from this glyph's centre line",
            ],
        },
    },
    "uni0260": {  # U+0260 ɠ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] crowded: macron 17 from the glyph (normally 105), circumflex 12 from the glyph (normally 72)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 1 of 3 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 60 other(s), a different letterform; -112 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (236, -110),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [aspect] glyph sits on aspect 'd' but y = -110 is the reference of an inner aspect, 128 inside the bottom of the glyph; 0 of 2 tested marks fit there",
                "bad [copy] same anchor as c (U+0063) and 6 other(s), a different letterform; -84 from this glyph's centre line",
            ],
        },
    },
    "uni0265": {  # U+0265 ɥ
        2: {  # below
            "xy": (219, -129),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron below 32 from the glyph (normally 78)',
                "suspect [reference] y = -129 is 19 from the nearest reference value (aspect 'd')",
            ],
        },
    },
    "uni0266": {  # U+0266 ɦ
        0: {  # above
            "xy": (299, 565),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot overlaps the glyph (1 of 3 marks tested)',
                "bad [reference] y = 565 is 80 from every reference value although the glyph sits on aspect 'a'",
            ],
        },
    },
    "uni0267": {  # U+0267 ɧ
        0: {  # above
            "xy": (299, 565),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot overlaps the glyph (1 of 3 marks tested)',
                "bad [reference] y = 565 is 80 from every reference value although the glyph sits on aspect 'a'",
            ],
        },
        2: {  # below
            "xy": (240, -114),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
            ],
        },
    },
    "uni026B": {  # U+026B ɫ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 60 other(s), a different letterform; +65 from this glyph's centre line",
            ],
        },
    },
    "uni026C": {  # U+026C ɬ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 0 of 3 tested marks fit there",
                "suspect [copy] same anchor as a (U+0061) and 60 other(s), a different letterform; +27 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (218, -120),
            "verdict": "suspect",
            "reasons": [
                "suspect [reference] y = -120 is 10 from the nearest reference value (aspect 'b')",
            ],
        },
    },
    "uni026D": {  # U+026D ɭ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; +27 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
            ],
        },
    },
    "uni026E": {  # U+026E ɮ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -42 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [aspect] glyph sits on aspect 'd' but y = -110 is the reference of an inner aspect, 125 inside the bottom of the glyph; 0 of 2 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -55 from this glyph's centre line",
            ],
        },
    },
    "uni0270": {  # U+0270 ɰ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), a different letterform; -170 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (294, -114),
            "verdict": "suspect",
            "reasons": [
                "suspect [aspect] glyph sits on aspect 'd' but y = -114 is the reference of an inner aspect, 124 inside the bottom of the glyph; 2 of 2 tested marks fit there",
            ],
        },
    },
    "uni0271": {  # U+0271 ɱ
        2: {  # below
            "xy": (383, -105),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron below 33 from the glyph (normally 78)',
            ],
        },
    },
    "uni0272": {  # U+0272 ɲ
        0: {  # above
            "xy": (264, 646),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as n (U+006E) and 2 other(s), as is its other anchor, a different letterform; +30 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (265, -111),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] crowded: macron below 3 from the glyph (normally 78)',
                "bad [copy] same anchor as n (U+006E) and 1 other(s), as is its other anchor, a different letterform; +30 from this glyph's centre line",
            ],
        },
    },
    "uni0273": {  # U+0273 ɳ
        2: {  # below
            "xy": (262, -112),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "suspect [copy] same anchor as L (U+004C) and 1 other(s), a different letterform; -34 from this glyph's centre line",
            ],
        },
    },
    "uni0274": {  # U+0274 ɴ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), a different letterform; -70 from this glyph's centre line",
            ],
        },
    },
    "uni0275": {  # U+0275 ɵ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -43 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -56 from this glyph's centre line",
            ],
        },
    },
    "uni0276": {  # U+0276 ɶ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -132 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -144 from this glyph's centre line",
            ],
        },
    },
    "uni0277": {  # U+0277 ɷ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), a different letterform; -148 from this glyph's centre line",
            ],
        },
    },
    "uni0278": {  # U+0278 ɸ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -76 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [aspect] glyph sits on aspect 'd' but y = -110 is the reference of an inner aspect, 124 inside the bottom of the glyph; 0 of 2 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -90 from this glyph's centre line",
            ],
        },
    },
    "uni0279": {  # U+0279 ɹ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), a different letterform; +32 from this glyph's centre line",
            ],
        },
    },
    "uni027A": {  # U+027A ɺ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "suspect [copy] same anchor as a (U+0061) and 60 other(s), a different letterform; +30 from this glyph's centre line",
            ],
        },
    },
    "uni027B": {  # U+027B ɻ
        2: {  # below
            "xy": (196, -110),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "suspect [copy] same anchor as a (U+0061) and 48 other(s), a different letterform; -30 from this glyph's centre line",
            ],
        },
    },
    "uni027C": {  # U+027C ɼ
        0: {  # above
            "xy": (222, 703),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 703 is 58 from every reference value although the glyph sits on aspect 'x'",
            ],
        },
        2: {  # below
            "xy": (127, -305),
            "verdict": "suspect",
            "reasons": [
                "suspect [reference] y = -305 is 14 from the nearest reference value (aspect 'd')",
                'suspect [style-position] anchor sits 31% across the glyph; 47% in the other styles',
            ],
        },
    },
    "uni027D": {  # U+027D ɽ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; +22 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [aspect] glyph sits on aspect 'd' but y = -110 is the reference of an inner aspect, 122 inside the bottom of the glyph; 0 of 2 tested marks fit there",
            ],
        },
    },
    "uni027E": {  # U+027E ɾ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; +34 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; +22 from this glyph's centre line",
            ],
        },
    },
    "uni027F": {  # U+027F ɿ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; +38 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; +26 from this glyph's centre line",
            ],
        },
    },
    "uni0280": {  # U+0280 ʀ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -30 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -43 from this glyph's centre line",
            ],
        },
    },
    "uni0281": {  # U+0281 ʁ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -30 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -43 from this glyph's centre line",
            ],
        },
    },
    "uni0282": {  # U+0282 ʂ
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
            ],
        },
    },
    "uni0283": {  # U+0283 ʃ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; +68 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; +56 from this glyph's centre line",
            ],
        },
    },
    "uni0284": {  # U+0284 ʄ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; +68 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; +56 from this glyph's centre line",
            ],
        },
    },
    "uni0285": {  # U+0285 ʅ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; +38 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; +26 from this glyph's centre line",
            ],
        },
    },
    "uni0286": {  # U+0286 ʆ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; +60 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; +46 from this glyph's centre line",
            ],
        },
    },
    "uni0287": {  # U+0287 ʇ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; +59 from this glyph's centre line",
                'suspect [turned] turned form of t (U+0074); anchor x is +59 from the transformed anchor of that letter',
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; +46 from this glyph's centre line",
            ],
        },
    },
    "uni0288": {  # U+0288 ʈ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; +52 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; +38 from this glyph's centre line",
            ],
        },
    },
    "uni0289": {  # U+0289 ʉ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -62 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -74 from this glyph's centre line",
            ],
        },
    },
    "uni028A": {  # U+028A ʊ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), a different letterform; -44 from this glyph's centre line",
            ],
        },
    },
    "uni028B": {  # U+028B ʋ
        0: {  # above
            "xy": (259, 645),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as ɣ (U+0263) and 1 other(s), a different letterform; +24 from this glyph's centre line",
            ],
        },
    },
    "uni028C": {  # U+028C ʌ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -35 from this glyph's centre line",
                'suspect [turned] turned form of v (U+0076); anchor x is -43 from the transformed anchor of that letter',
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -48 from this glyph's centre line",
                'suspect [turned] turned form of v (U+0076); anchor x is -41 from the transformed anchor of that letter',
            ],
        },
    },
    "uni028D": {  # U+028D ʍ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -158 from this glyph's centre line",
                'suspect [turned] turned form of w (U+0077); anchor x is -179 from the transformed anchor of that letter',
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -171 from this glyph's centre line",
                'suspect [turned] turned form of w (U+0077); anchor x is -199 from the transformed anchor of that letter',
            ],
        },
    },
    "uni028E": {  # U+028E ʎ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -38 from this glyph's centre line",
                'suspect [turned] turned form of y (U+0079); anchor x is -56 from the transformed anchor of that letter',
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -52 from this glyph's centre line",
                'suspect [turned] turned form of y (U+0079); anchor x is -49 from the transformed anchor of that letter',
            ],
        },
    },
    "uni028F": {  # U+028F ʏ
        0: {  # above
            "xy": (209, 645),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as a (U+0061) and 60 other(s), a different letterform; -26 from this glyph's centre line",
            ],
        },
    },
    "uni0290": {  # U+0290 ʐ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -53 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -66 from this glyph's centre line",
            ],
        },
    },
    "uni0291": {  # U+0291 ʑ
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -22 from this glyph's centre line",
            ],
        },
    },
    "uni0293": {  # U+0293 ʓ
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [aspect] glyph sits on aspect 'd' but y = -110 is the reference of an inner aspect, 128 inside the bottom of the glyph; 0 of 2 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -24 from this glyph's centre line",
            ],
        },
    },
    "uni0294": {  # U+0294 ʔ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'c' but y = 645 is the reference of an inner aspect, 11 inside the top of the glyph; 0 of 3 tested marks fit there",
            ],
        },
    },
    "uni0295": {  # U+0295 ʕ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'c' but y = 645 is the reference of an inner aspect, 11 inside the top of the glyph; 0 of 3 tested marks fit there",
            ],
        },
    },
    "uni0296": {  # U+0296 ʖ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'c' but y = 645 is the reference of an inner aspect, 2 inside the top of the glyph; 0 of 3 tested marks fit there",
            ],
        },
    },
    "uni0297": {  # U+0297 ʗ
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -25 from this glyph's centre line",
            ],
        },
    },
    "uni0298": {  # U+0298 ʘ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -148 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -160 from this glyph's centre line",
            ],
        },
    },
    "uni0299": {  # U+0299 ʙ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -24 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -37 from this glyph's centre line",
            ],
        },
    },
    "uni029A": {  # U+029A ʚ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -28 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -42 from this glyph's centre line",
            ],
        },
    },
    "uni029B": {  # U+029B ʛ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -85 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -98 from this glyph's centre line",
            ],
        },
    },
    "uni029C": {  # U+029C ʜ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), a different letterform; -84 from this glyph's centre line",
            ],
        },
    },
    "uni029D": {  # U+029D ʝ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; +83 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; +70 from this glyph's centre line",
            ],
        },
    },
    "uni029E": {  # U+029E ʞ
        2: {  # below
            "xy": (193, -107),
            "verdict": "suspect",
            "reasons": [
                "suspect [aspect] glyph sits on aspect 'd' but y = -107 is the reference of an inner aspect, 131 inside the bottom of the glyph; 2 of 2 tested marks fit there",
            ],
        },
    },
    "uni02A0": {  # U+02A0 ʠ
        0: {  # above
            "xy": (238, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 1 of 3 tested marks fit there",
                "suspect [copy] same anchor as o (U+006F) and 1 other(s), a different letterform; -82 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] crowded: dot below 31 from the glyph (normally 95)',
                "suspect [aspect] glyph sits on aspect 'd' but y = -110 is the reference of an inner aspect, 124 inside the bottom of the glyph; 1 of 2 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 48 other(s), a different letterform; -124 from this glyph's centre line",
            ],
        },
    },
    "uni02A1": {  # U+02A1 ʡ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
            ],
        },
    },
    "uni02A2": {  # U+02A2 ʢ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -25 from this glyph's centre line",
                "bad [turned] reversed form of ʡ (U+02A1) but carries that letter's anchor unchanged; -40 from where the transformation puts it",
            ],
        },
    },
    "uni02A3": {  # U+02A3 ʣ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] crowded: macron 7 from the glyph (normally 105), circumflex 9 from the glyph (normally 72)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 1 of 3 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -207 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -220 from this glyph's centre line",
            ],
        },
    },
    "uni02A4": {  # U+02A4 ʤ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] crowded: macron 9 from the glyph (normally 105), circumflex 11 from the glyph (normally 72)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 1 of 3 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -172 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "suspect [aspect] glyph sits on aspect 'd' but y = -110 is the reference of an inner aspect, 125 inside the bottom of the glyph; 2 of 2 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -185 from this glyph's centre line",
            ],
        },
    },
    "uni02A5": {  # U+02A5 ʥ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] crowded: macron 9 from the glyph (normally 105), circumflex 11 from the glyph (normally 72)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 1 of 3 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -210 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -222 from this glyph's centre line",
            ],
        },
    },
    "uni02A6": {  # U+02A6 ʦ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -82 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -95 from this glyph's centre line",
            ],
        },
    },
    "uni02A7": {  # U+02A7 ʧ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 44 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -67 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -80 from this glyph's centre line",
            ],
        },
    },
    "uni02A8": {  # U+02A8 ʨ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -111 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -124 from this glyph's centre line",
            ],
        },
    },
    "uni02A9": {  # U+02A9 ʩ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -168 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -182 from this glyph's centre line",
            ],
        },
    },
    "uni02AA": {  # U+02AA ʪ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -50 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -63 from this glyph's centre line",
            ],
        },
    },
    "uni02AB": {  # U+02AB ʫ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -92 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -105 from this glyph's centre line",
            ],
        },
    },
    "uni02AC": {  # U+02AC ʬ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [copy] same anchor as a (U+0061) and 60 other(s), as is its other anchor, a different letterform; -20 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as a (U+0061) and 48 other(s), as is its other anchor, a different letterform; -33 from this glyph's centre line",
            ],
        },
    },
    "uni02AE": {  # U+02AE ʮ
        0: {  # above
            "xy": (278, -214),
            "verdict": "bad",
            "reasons": [
                'bad [side] above anchor at y = -214, in the lower half of the glyph or below it',
                'suspect [collision] crowded: macron 48 from the glyph (normally 105)',
                'bad [reference] y = -214 is 859 from every reference value',
            ],
        },
        2: {  # below
            "xy": (318, 542),
            "verdict": "bad",
            "reasons": [
                'bad [side] below anchor at y = 542, in the upper half of the glyph or above it',
                'suspect [collision] crowded: dot below 15 from the glyph (normally 95)',
                'bad [reference] y = 542 is 652 from every reference value',
            ],
        },
    },
    "uni02AF": {  # U+02AF ʯ
        0: {  # above
            "xy": (278, -214),
            "verdict": "bad",
            "reasons": [
                'bad [side] above anchor at y = -214, in the lower half of the glyph or below it',
                'bad [reference] y = -214 is 859 from every reference value',
                "bad [copy] same anchor as ʮ (U+02AE), as is its other anchor, a different letterform; -50 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (318, 542),
            "verdict": "bad",
            "reasons": [
                'bad [side] below anchor at y = 542, in the upper half of the glyph or above it',
                'suspect [collision] crowded: dot below 15 from the glyph (normally 95)',
                'bad [reference] y = 542 is 652 from every reference value',
            ],
        },
    },
    "beta": {  # U+03B2 β
        2: {  # below
            "xy": (275, -114),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron below 8 from the glyph (normally 78)',
                "suspect [aspect] glyph sits on aspect 'd' but y = -114 is the reference of an inner aspect, 124 inside the bottom of the glyph; 1 of 2 tested marks fit there",
            ],
        },
    },
    "uni0404": {  # U+0404 Є
        0: {  # above
            "xy": (340, 850),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as C (U+0043), as is its other anchor, a different letterform; +35 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (363, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as C (U+0043) and 1 other(s), as is its other anchor, a different letterform; +58 from this glyph's centre line",
            ],
        },
    },
    "uni040B": {  # U+040B Ћ
        0: {  # above
            "xy": (300, 802),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 802 is 48 from every reference value although the glyph sits on aspect 'c'",
            ],
        },
    },
    "uni041A": {  # U+041A К
        0: {  # above
            "xy": (336, 850),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as K (U+004B) and 1 other(s), as is its other anchor, a different letterform; +27 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (342, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as K (U+004B) and 1 other(s), as is its other anchor, a different letterform; +33 from this glyph's centre line",
            ],
        },
    },
    "uni043D": {  # U+043D н
        0: {  # above
            "xy": (297, 685),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 685 is 40 from every reference value although the glyph sits on aspect 'x'",
            ],
        },
    },
    "uni045A": {  # U+045A њ
        0: {  # above
            "xy": (297, 685),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 685 is 40 from every reference value although the glyph sits on aspect 'x'",
                "bad [copy] same anchor as н (U+043D), as is its other anchor, a different letterform; -79 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (304, -110),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as н (U+043D), as is its other anchor, a different letterform; -72 from this glyph's centre line",
            ],
        },
    },
    "uni1D47": {  # U+1D47 ᵇ
        0: {  # above
            "xy": (148, 815),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
            ],
        },
    },
    "uni1ECD": {  # U+1ECD ọ
        0: {  # above
            "xy": (231, 645),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as g (U+0067) and 4 other(s), a different letterform; -21 from this glyph's centre line",
            ],
        },
    },
    "uni1EFA": {  # U+1EFA Ỻ
        0: {  # above
            "xy": (276, 804),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 804 is 46 from every reference value although the glyph sits on aspect 'c'",
            ],
        },
    },
    "uni2132": {  # U+2132 Ⅎ
        0: {  # above
            "xy": (201, -203),
            "verdict": "bad",
            "reasons": [
                'bad [side] above anchor at y = -203, in the lower half of the glyph or below it',
                'bad [reference] y = -203 is 848 from every reference value',
                'suspect [turned] turned form of F (U+0046); anchor x is -75 from the transformed anchor of that letter',
            ],
        },
        2: {  # below
            "xy": (276, 757),
            "verdict": "bad",
            "reasons": [
                'bad [side] below anchor at y = 757, in the upper half of the glyph or above it',
                'suspect [collision] crowded: dot below 9 from the glyph (normally 95)',
                'bad [reference] y = 757 is 867 from every reference value',
                'suspect [turned] turned form of F (U+0046); anchor x is +75 from the transformed anchor of that letter',
            ],
        },
    },
    "uni2184": {  # U+2184 ↄ
        2: {  # below
            "xy": (186, -113),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as ə (U+0259), a different letterform; -16 from this glyph's centre line",
            ],
        },
    },
    "uni2C68": {  # U+2C68 ⱨ
        0: {  # above
            "xy": (299, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron 3 from the glyph (normally 105), circumflex 10 from the glyph (normally 72)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 1 of 3 tested marks fit there",
            ],
        },
    },
    "uni2C69": {  # U+2C69 Ⱪ
        0: {  # above
            "xy": (336, 798),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 798 is 52 from every reference value although the glyph sits on aspect 'c'",
            ],
        },
        2: {  # below
            "xy": (342, -109),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as K (U+004B) and 1 other(s), a different letterform; +16 from this glyph's centre line",
            ],
        },
    },
    "uni2C6A": {  # U+2C6A ⱪ
        0: {  # above
            "xy": (275, 646),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 646 is the reference of an inner aspect, 52 inside the top of the glyph; 1 of 3 tested marks fit there",
            ],
        },
    },
    "uni2C6B": {  # U+2C6B Ⱬ
        0: {  # above
            "xy": (320, 803),
            "verdict": "suspect",
            "reasons": [
                "suspect [reference] y = 803 is 47 from both the reference values and the clearance rule (aspect 'c+22')",
            ],
        },
    },
    "uni2C6C": {  # U+2C6C ⱬ
        2: {  # below
            "xy": (204, -111),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron below 17 from the glyph (normally 78)',
            ],
        },
    },
    "uni2C6E": {  # U+2C6E Ɱ
        2: {  # below
            "xy": (393, -110),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
            ],
        },
    },
    "uni2C74": {  # U+2C74 ⱴ
        2: {  # below
            "xy": (229, -113),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as ɐ (U+0250), a different letterform; -26 from this glyph's centre line",
            ],
        },
    },
}
