# Generated by run_anchor_audit.py. Do not edit: rerunning overwrites this file.
# To overrule a verdict, add an entry to data/fontanchors_audit/overrides.py.
#
# semibold: 77 anchors audited; 3 bad, 9 suspect, 65 ok
# anchor class 0 = above, 2 = below

audit = {
    "g": {  # U+0067 g
        2: {  # below
            "xy": (229, -319),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: dot below 34 from the glyph (normally 59)',
            ],
        },
    },
    "j": {  # U+006A j
        2: {  # below
            "xy": (109, -319),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as J (U+004A), a different letterform; +31 from this glyph's centre line",
            ],
        },
    },
    "AE": {  # U+00C6 Æ
        0: {  # above
            "xy": (510, 850),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 850 is 35 from every reference value although the glyph sits on aspect 'c'",
                'suspect [precomposed] precomposed glyphs centre marks +60 from this anchor (1 glyph(s) compared)',
            ],
        },
    },
    "dotlessi": {  # U+0131 ı
        2: {  # below
            "xy": (135, -108),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as l (U+006C), a different letterform; -20 from this glyph's centre line",
            ],
        },
    },
    "OE": {  # U+0152 Œ
        0: {  # above
            "xy": (450, 850),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 850 is 35 from every reference value although the glyph sits on aspect 'c'",
            ],
        },
    },
    "uni0186": {  # U+0186 Ɔ
        0: {  # above
            "xy": (275, 833),
            "verdict": "suspect",
            "reasons": [
                "suspect [reference] y = 833 is 28 from the nearest reference value (aspect 'c')",
            ],
        },
    },
    "uni0237": {  # U+0237 ȷ
        0: {  # above
            "xy": (163, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [centre] anchor x is +85 from the centre line (30% of the width)',
                'suspect [style-position] anchor sits 80% across the glyph; 49% in the other styles',
            ],
        },
    },
    "uni026C": {  # U+026C ɬ
        2: {  # below
            "xy": (218, -120),
            "verdict": "suspect",
            "reasons": [
                "suspect [reference] y = -120 is 10 from the nearest reference value (aspect 'b')",
            ],
        },
    },
    "uni0279": {  # U+0279 ɹ
        2: {  # below
            "xy": (190, -114),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -33 from that style's; +46 off centre here (+13 there)",
            ],
        },
    },
    "uni1ECC": {  # U+1ECC Ọ
        0: {  # above
            "xy": (363, 833),
            "verdict": "suspect",
            "reasons": [
                "suspect [reference] y = 833 is 28 from the nearest reference value (aspect 'c')",
            ],
        },
    },
    "uni1EE4": {  # U+1EE4 Ụ
        0: {  # above
            "xy": (362, 833),
            "verdict": "suspect",
            "reasons": [
                "suspect [reference] y = 833 is 28 from the nearest reference value (aspect 'c')",
            ],
        },
    },
    "uni2139": {  # U+2139 ℹ
        2: {  # below
            "xy": (136, -107),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as i (U+0069), a different letterform; -18 from this glyph's centre line",
            ],
        },
    },
}
