# Generated by run_anchor_audit.py. Do not edit: rerunning overwrites this file.
# To overrule a verdict, add an entry to data/fontanchors_audit/overrides.py.
#
# semibold_italic: 326 anchors audited; 166 bad, 39 suspect, 121 ok
# anchor class 0 = above, 2 = below

audit = {
    "A": {  # U+0041 A
        0: {  # above
            "xy": (354, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +157 from this anchor (7 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +188 from that style's; -180 off centre here (+8 there)",
                'suspect [style-position] anchor sits 24% across the glyph; 50% in the other styles',
            ],
        },
    },
    "B": {  # U+0042 B
        0: {  # above
            "xy": (267, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -173 from the centre line (31% of the width)',
                'suspect [precomposed] precomposed glyphs centre marks +208 from this anchor (1 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +159 from that style's; -173 off centre here (-14 there)",
                'suspect [style-position] anchor sits 19% across the glyph; 49% in the other styles',
            ],
        },
    },
    "C": {  # U+0043 C
        0: {  # above
            "xy": (340, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +157 from this anchor (3 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +162 from that style's; -146 off centre here (+16 there)",
                'suspect [style-position] anchor sits 25% across the glyph; 53% in the other styles',
            ],
        },
        2: {  # below
            "xy": (363, -110),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -34 from that style's; +73 off centre here (+39 there)",
            ],
        },
    },
    "D": {  # U+0044 D
        0: {  # above
            "xy": (306, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +128 from this anchor (2 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +161 from that style's; -191 off centre here (-30 there)",
                'suspect [style-position] anchor sits 20% across the glyph; 40% in the other styles',
            ],
        },
    },
    "E": {  # U+0045 E
        0: {  # above
            "xy": (273, 850),
            "verdict": "suspect",
            "reasons": [
                'suspect [centre] anchor x is -160 from the centre line (31% of the width)',
                'suspect [precomposed] precomposed glyphs centre marks +140 from this anchor (7 glyph(s) compared)',
                'suspect [style-position] anchor sits 19% across the glyph; 49% in the other styles',
            ],
        },
    },
    "F": {  # U+0046 F
        0: {  # above
            "xy": (276, 850),
            "verdict": "suspect",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +203 from this anchor (1 glyph(s) compared)',
                'suspect [style-position] anchor sits 21% across the glyph; 55% in the other styles',
            ],
        },
    },
    "G": {  # U+0047 G
        0: {  # above
            "xy": (365, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +152 from this anchor (5 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +167 from that style's; -154 off centre here (+14 there)",
                'suspect [style-position] anchor sits 26% across the glyph; 51% in the other styles',
            ],
        },
        2: {  # below
            "xy": (367, -110),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -28 from that style's; +44 off centre here (+16 there)",
            ],
        },
    },
    "H": {  # U+0048 H
        0: {  # above
            "xy": (361, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +165 from this anchor (4 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +191 from that style's; -192 off centre here (-1 there)",
                'suspect [style-position] anchor sits 22% across the glyph; 48% in the other styles',
            ],
        },
    },
    "I": {  # U+0049 I
        0: {  # above
            "xy": (150, 850),
            "verdict": "bad",
            "reasons": [
                'bad [extent] anchor x is 40 outside the glyph, to the left',
                'suspect [precomposed] precomposed glyphs centre marks +184 from this anchor (7 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +203 from that style's; -202 off centre here (+2 there)",
                'suspect [style-position] anchor sits -12% across the glyph; 50% in the other styles',
            ],
        },
    },
    "J": {  # U+004A J
        2: {  # below
            "xy": (109, -319),
            "verdict": "bad",
            "reasons": [
                'suspect [clearance] anchor is 155 clear of the glyph; the largest normal clearance is 110',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +31 from that style's; -42 off centre here (-11 there)",
            ],
        },
    },
    "K": {  # U+004B K
        0: {  # above
            "xy": (336, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +180 from this anchor (1 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +207 from that style's; -194 off centre here (+13 there)",
                'suspect [style-position] anchor sits 20% across the glyph; 50% in the other styles',
            ],
        },
    },
    "L": {  # U+004C L
        0: {  # above
            "xy": (149, 850),
            "verdict": "bad",
            "reasons": [
                'bad [extent] anchor x is 65 outside the glyph, to the left',
                'suspect [style-position] anchor sits -13% across the glyph; 35% in the other styles',
            ],
        },
    },
    "M": {  # U+004D M
        0: {  # above
            "xy": (431, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +158 from this anchor (1 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +171 from that style's; -158 off centre here (+14 there)",
                'suspect [style-position] anchor sits 30% across the glyph; 49% in the other styles',
            ],
        },
    },
    "N": {  # U+004E N
        0: {  # above
            "xy": (346, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +184 from this anchor (3 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +177 from that style's; -184 off centre here (-8 there)",
                'suspect [style-position] anchor sits 25% across the glyph; 47% in the other styles',
            ],
        },
    },
    "O": {  # U+004F O
        0: {  # above
            "xy": (335, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -208 from the centre line (32% of the width)',
                'suspect [precomposed] precomposed glyphs centre marks +179 from this anchor (7 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +192 from that style's; -208 off centre here (-16 there)",
                'suspect [style-position] anchor sits 18% across the glyph; 50% in the other styles',
            ],
        },
    },
    "P": {  # U+0050 P
        0: {  # above
            "xy": (316, 850),
            "verdict": "suspect",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +135 from this anchor (1 glyph(s) compared)',
                'suspect [style-position] anchor sits 29% across the glyph; 53% in the other styles',
            ],
        },
    },
    "Q": {  # U+0051 Q
        0: {  # above
            "xy": (348, 850),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +184 from that style's; -195 off centre here (-11 there)",
                'suspect [style-position] anchor sits 20% across the glyph; 48% in the other styles',
            ],
        },
    },
    "R": {  # U+0052 R
        0: {  # above
            "xy": (269, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -203 from the centre line (35% of the width)',
                'suspect [precomposed] precomposed glyphs centre marks +174 from this anchor (2 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +171 from that style's; -203 off centre here (-32 there)",
                'suspect [style-position] anchor sits 15% across the glyph; 44% in the other styles',
            ],
        },
        2: {  # below
            "xy": (258, -110),
            "verdict": "suspect",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +55 from this anchor (2 glyph(s) compared)',
            ],
        },
    },
    "S": {  # U+0053 S
        0: {  # above
            "xy": (232, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -163 from the centre line (42% of the width)',
                'suspect [precomposed] precomposed glyphs centre marks +160 from this anchor (3 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +159 from that style's; -163 off centre here (-4 there)",
                'suspect [style-position] anchor sits 8% across the glyph; 50% in the other styles',
            ],
        },
    },
    "T": {  # U+0054 T
        0: {  # above
            "xy": (307, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +154 from this anchor (2 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +149 from that style's; -139 off centre here (+10 there)",
                'suspect [style-position] anchor sits 25% across the glyph; 51% in the other styles',
            ],
        },
    },
    "U": {  # U+0055 U
        0: {  # above
            "xy": (346, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +166 from this anchor (7 glyph(s) compared)',
                "suspect [copy] same anchor as N (U+004E) and 1 other(s), a different letterform; -169 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +184 from that style's; -169 off centre here (+15 there)",
                'suspect [style-position] anchor sits 25% across the glyph; 51% in the other styles',
            ],
        },
    },
    "V": {  # U+0056 V
        0: {  # above
            "xy": (336, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +192 from this anchor (1 glyph(s) compared)',
                "suspect [copy] same anchor as K (U+004B), a different letterform; -126 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +136 from that style's; -126 off centre here (+11 there)",
                'suspect [style-position] anchor sits 29% across the glyph; 52% in the other styles',
            ],
        },
    },
    "W": {  # U+0057 W
        0: {  # above
            "xy": (450, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +171 from this anchor (3 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +152 from that style's; -175 off centre here (-24 there)",
                'suspect [style-position] anchor sits 31% across the glyph; 48% in the other styles',
            ],
        },
    },
    "X": {  # U+0058 X
        0: {  # above
            "xy": (332, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +162 from this anchor (2 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +189 from that style's; -181 off centre here (+9 there)",
                'suspect [style-position] anchor sits 23% across the glyph; 51% in the other styles',
            ],
        },
    },
    "Y": {  # U+0059 Y
        0: {  # above
            "xy": (295, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +155 from this anchor (5 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +165 from that style's; -157 off centre here (+8 there)",
                'suspect [style-position] anchor sits 23% across the glyph; 51% in the other styles',
            ],
        },
        2: {  # below
            "xy": (295, -110),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -30 from that style's; +38 off centre here (+8 there)",
            ],
        },
    },
    "Z": {  # U+005A Z
        0: {  # above
            "xy": (320, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +132 from this anchor (3 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +157 from that style's; -147 off centre here (+10 there)",
                'suspect [style-position] anchor sits 23% across the glyph; 52% in the other styles',
            ],
        },
    },
    "a": {  # U+0061 a
        2: {  # below
            "xy": (196, -110),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +37 from this anchor (2 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +25 from that style's; -75 off centre here (-50 there)",
            ],
        },
    },
    "c": {  # U+0063 c
        0: {  # above
            "xy": (242, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -115 from the centre line (30% of the width)',
                'suspect [precomposed] precomposed glyphs centre marks +123 from this anchor (3 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +139 from that style's; -115 off centre here (+24 there)",
                'suspect [style-position] anchor sits 20% across the glyph; 53% in the other styles',
            ],
        },
    },
    "d": {  # U+0064 d
        0: {  # above
            "xy": (218, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -200 from the centre line (40% of the width)',
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 0 of 3 tested marks fit there",
                'suspect [precomposed] precomposed glyphs centre marks +88 from this anchor (1 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +147 from that style's; -200 off centre here (-52 there)",
            ],
        },
    },
    "e": {  # U+0065 e
        0: {  # above
            "xy": (243, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -125 from the centre line (32% of the width)',
                'suspect [precomposed] precomposed glyphs centre marks +137 from this anchor (7 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +146 from that style's; -125 off centre here (+21 there)",
                'suspect [style-position] anchor sits 18% across the glyph; 51% in the other styles',
            ],
        },
    },
    "f": {  # U+0066 f
        2: {  # below
            "xy": (132, -110),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [aspect] glyph sits on aspect 'd' but y = -110 is the reference of an inner aspect, 128 inside the bottom of the glyph; 0 of 2 tested marks fit there",
            ],
        },
    },
    "g": {  # U+0067 g
        0: {  # above
            "xy": (291, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +64 from this anchor (5 glyph(s) compared)',
                'suspect [style-position] anchor sits 29% across the glyph; 44% in the other styles',
            ],
        },
        2: {  # below
            "xy": (199, -319),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron below 7 from the glyph (normally 25)',
            ],
        },
    },
    "h": {  # U+0068 h
        0: {  # above
            "xy": (469, 645),
            "verdict": "suspect",
            "reasons": [
                "suspect [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 3 of 3 tested marks fit there",
            ],
        },
    },
    "i": {  # U+0069 i
        0: {  # above
            "xy": (137, 795),
            "verdict": "bad",
            "reasons": [
                'bad [extent] anchor x is 55 outside the glyph, to the left',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +194 from that style's; -199 off centre here (-4 there)",
                'suspect [style-position] anchor sits -19% across the glyph; 45% in the other styles',
            ],
        },
    },
    "k": {  # U+006B k
        0: {  # above
            "xy": (306, 784),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "bad [reference] y = 784 is 66 from every reference value although the glyph sits on aspect 'a'",
                'suspect [precomposed] precomposed glyphs centre marks +197 from this anchor (1 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +182 from that style's; -137 off centre here (+45 there)",
            ],
        },
        2: {  # below
            "xy": (290, -214),
            "verdict": "bad",
            "reasons": [
                'bad [reference] y = -214 is 104 from every reference value',
                'suspect [precomposed] precomposed glyphs centre marks -44 from this anchor (2 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -21 from that style's; +50 off centre here (+29 there)",
            ],
        },
    },
    "l": {  # U+006C l
        0: {  # above
            "xy": (174, 890),
            "verdict": "bad",
            "reasons": [
                'bad [extent] anchor x is 29 outside the glyph, to the left',
                'suspect [style-position] anchor sits -10% across the glyph; 47% in the other styles',
            ],
        },
    },
    "m": {  # U+006D m
        0: {  # above
            "xy": (392, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +170 from this anchor (1 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +161 from that style's; -170 off centre here (-9 there)",
                'suspect [style-position] anchor sits 29% across the glyph; 48% in the other styles',
            ],
        },
    },
    "n": {  # U+006E n
        0: {  # above
            "xy": (264, 646),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -170 from the centre line (30% of the width)',
                'suspect [precomposed] precomposed glyphs centre marks +157 from this anchor (3 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +159 from that style's; -170 off centre here (-11 there)",
                'suspect [style-position] anchor sits 20% across the glyph; 48% in the other styles',
            ],
        },
    },
    "o": {  # U+006F o
        0: {  # above
            "xy": (238, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -143 from the centre line (33% of the width)',
                'suspect [precomposed] precomposed glyphs centre marks +123 from this anchor (7 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +129 from that style's; -143 off centre here (-14 there)",
                'suspect [style-position] anchor sits 17% across the glyph; 48% in the other styles',
            ],
        },
    },
    "p": {  # U+0070 p
        0: {  # above
            "xy": (271, 646),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] crowded: circumflex 33 from the glyph (normally 65)',
                'suspect [precomposed] precomposed glyphs centre marks +158 from this anchor (1 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +141 from that style's; -112 off centre here (+29 there)",
                'suspect [style-position] anchor sits 27% across the glyph; 58% in the other styles',
            ],
        },
        2: {  # below
            "xy": (179, -319),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron below 10 from the glyph (normally 25)',
            ],
        },
    },
    "q": {  # U+0071 q
        0: {  # above
            "xy": (238, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -182 from the centre line (37% of the width)',
                "suspect [copy] same anchor as o (U+006F) and 1 other(s), a different letterform; -182 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +151 from that style's; -182 off centre here (-30 there)",
                'suspect [style-position] anchor sits 13% across the glyph; 43% in the other styles',
            ],
        },
        2: {  # below
            "xy": (348, -319),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] crowded: macron below 10 from the glyph (normally 25)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -45 from that style's; +124 off centre here (+80 there)",
                'suspect [style-position] anchor sits 75% across the glyph; 51% in the other styles',
            ],
        },
    },
    "r": {  # U+0072 r
        0: {  # above
            "xy": (191, 646),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -162 from the centre line (40% of the width)',
                'suspect [precomposed] precomposed glyphs centre marks +158 from this anchor (2 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +163 from that style's; -162 off centre here (+1 there)",
                'suspect [style-position] anchor sits 10% across the glyph; 49% in the other styles',
            ],
        },
    },
    "u": {  # U+0075 u
        0: {  # above
            "xy": (255, 645),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +141 from that style's; -157 off centre here (-16 there)",
                'suspect [style-position] anchor sits 21% across the glyph; 47% in the other styles',
            ],
        },
    },
    "v": {  # U+0076 v
        0: {  # above
            "xy": (256, 646),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +106 from this anchor (1 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +120 from that style's; -113 off centre here (+7 there)",
            ],
        },
    },
    "w": {  # U+0077 w
        0: {  # above
            "xy": (345, 646),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +152 from this anchor (4 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +103 from that style's; -131 off centre here (-28 there)",
            ],
        },
        2: {  # below
            "xy": (352, -110),
            "verdict": "suspect",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +30 from this anchor (1 glyph(s) compared)',
            ],
        },
    },
    "y": {  # U+0079 y
        0: {  # above
            "xy": (262, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +114 from this anchor (6 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +118 from that style's; -116 off centre here (+2 there)",
                'suspect [style-position] anchor sits 25% across the glyph; 49% in the other styles',
            ],
        },
        2: {  # below
            "xy": (242, -319),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +101 from this anchor (1 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -78 from that style's; +61 off centre here (-18 there)",
            ],
        },
    },
    "z": {  # U+007A z
        0: {  # above
            "xy": (220, 646),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -144 from the centre line (35% of the width)',
                'suspect [precomposed] precomposed glyphs centre marks +123 from this anchor (3 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +143 from that style's; -144 off centre here (-0 there)",
                'suspect [style-position] anchor sits 15% across the glyph; 50% in the other styles',
            ],
        },
    },
    "AE": {  # U+00C6 Æ
        0: {  # above
            "xy": (500, 850),
            "verdict": "suspect",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +214 from this anchor (1 glyph(s) compared)',
                'suspect [style-position] anchor sits 38% across the glyph; 55% in the other styles',
            ],
        },
        2: {  # below
            "xy": (549, -107),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -23 from that style's; +146 off centre here (+122 there)",
            ],
        },
    },
    "Ccedilla": {  # U+00C7 Ç
        0: {  # above
            "xy": (371, 850),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +162 from that style's; -115 off centre here (+47 there)",
            ],
        },
    },
    "Egrave": {  # U+00C8 È
        2: {  # below
            "xy": (279, -107),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -32 from that style's; +40 off centre here (+8 there)",
            ],
        },
    },
    "Eacute": {  # U+00C9 É
        2: {  # below
            "xy": (279, -107),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -32 from that style's; +40 off centre here (+8 there)",
            ],
        },
    },
    "Ecircumflex": {  # U+00CA Ê
        2: {  # below
            "xy": (279, -107),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -32 from that style's; +40 off centre here (+8 there)",
            ],
        },
    },
    "Edieresis": {  # U+00CB Ë
        2: {  # below
            "xy": (279, -107),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -32 from that style's; +40 off centre here (+8 there)",
            ],
        },
    },
    "Eth": {  # U+00D0 Ð
        0: {  # above
            "xy": (341, 850),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +164 from that style's; -156 off centre here (+8 there)",
            ],
        },
    },
    "Oslash": {  # U+00D8 Ø
        0: {  # above
            "xy": (351, 850),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +192 from that style's; -192 off centre here (-0 there)",
            ],
        },
    },
    "Thorn": {  # U+00DE Þ
        0: {  # above
            "xy": (281, 850),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +185 from that style's; -153 off centre here (+31 there)",
            ],
        },
    },
    "ae": {  # U+00E6 æ
        0: {  # above
            "xy": (350, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [precomposed] precomposed glyphs centre marks +149 from this anchor (1 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +157 from that style's; -150 off centre here (+6 there)",
                'suspect [style-position] anchor sits 27% across the glyph; 49% in the other styles',
            ],
        },
    },
    "ccedilla": {  # U+00E7 ç
        0: {  # above
            "xy": (255, 834),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -140 from the centre line (37% of the width)',
                "suspect [reference] y = 834 is 16 from the nearest reference value (aspect 'x')",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +178 from that style's; -140 off centre here (+38 there)",
            ],
        },
    },
    "thorn": {  # U+00FE þ
        0: {  # above
            "xy": (278, 646),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 646 is the reference of an inner aspect, 52 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +151 from that style's; -110 off centre here (+42 there)",
            ],
        },
    },
    "amacron": {  # U+0101 ā
        2: {  # below
            "xy": (196, -108),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +26 from that style's; -75 off centre here (-50 there)",
            ],
        },
    },
    "Aogonek": {  # U+0104 Ą
        0: {  # above
            "xy": (365, 850),
            "verdict": "bad",
            "reasons": [
                "suspect [copy] same anchor as G (U+0047), a different letterform; -172 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +185 from that style's; -172 off centre here (+13 there)",
            ],
        },
    },
    "aogonek": {  # U+0105 ą
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -230 from the centre line (44% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +191 from that style's; -230 off centre here (-39 there)",
            ],
        },
        2: {  # below
            "xy": (146, -108),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +37 from that style's; -139 off centre here (-102 there)",
            ],
        },
    },
    "emacron": {  # U+0113 ē
        2: {  # below
            "xy": (236, -110),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as c (U+0063) and 5 other(s), a different letterform; +22 from this glyph's centre line",
            ],
        },
    },
    "ebreve": {  # U+0115 ĕ
        2: {  # below
            "xy": (236, -110),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as c (U+0063) and 5 other(s), a different letterform; +22 from this glyph's centre line",
            ],
        },
    },
    "edotaccent": {  # U+0117 ė
        2: {  # below
            "xy": (236, -110),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as c (U+0063) and 5 other(s), a different letterform; +22 from this glyph's centre line",
            ],
        },
    },
    "eogonek": {  # U+0119 ę
        0: {  # above
            "xy": (231, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -137 from the centre line (35% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +146 from that style's; -137 off centre here (+9 there)",
            ],
        },
        2: {  # below
            "xy": (70, -108),
            "verdict": "suspect",
            "reasons": [
                'suspect [centre] anchor x is -144 from the centre line (37% of the width)',
                'suspect [collision] crowded: macron below 11 from the glyph (normally 25)',
            ],
        },
    },
    "Iogonek": {  # U+012E Į
        0: {  # above
            "xy": (146, 850),
            "verdict": "bad",
            "reasons": [
                'bad [extent] anchor x is 44 outside the glyph, to the left',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +203 from that style's; -206 off centre here (-2 there)",
            ],
        },
    },
    "iogonek": {  # U+012F į
        0: {  # above
            "xy": (132, 775),
            "verdict": "bad",
            "reasons": [
                'bad [extent] anchor x is 56 outside the glyph, to the left',
            ],
        },
    },
    "dotlessi": {  # U+0131 ı
        0: {  # above
            "xy": (132, 645),
            "verdict": "bad",
            "reasons": [
                'bad [extent] anchor x is 32 outside the glyph, to the left',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +166 from that style's; -175 off centre here (-10 there)",
                'suspect [style-position] anchor sits -11% across the glyph; 46% in the other styles',
            ],
        },
    },
    "kgreenlandic": {  # U+0138 ĸ
        0: {  # above
            "xy": (240, 644),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -166 from the centre line (34% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +139 from that style's; -166 off centre here (-27 there)",
                'suspect [style-position] anchor sits 16% across the glyph; 47% in the other styles',
            ],
        },
        2: {  # below
            "xy": (132, -108),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: macron below 12 from the glyph (normally 25)',
                "suspect [copy] same anchor as f (U+0066), a different letterform; -121 from this glyph's centre line",
            ],
        },
    },
    "Eng": {  # U+014A Ŋ
        0: {  # above
            "xy": (359, 804),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 804 is 46 from every reference value although the glyph sits on aspect 'c'",
            ],
        },
        2: {  # below
            "xy": (373, -109),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
            ],
        },
    },
    "eng": {  # U+014B ŋ
        0: {  # above
            "xy": (264, 646),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +146 from that style's; -122 off centre here (+24 there)",
            ],
        },
        2: {  # below
            "xy": (265, -111),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [copy] same anchor as n (U+006E) and 2 other(s), as is its other anchor, a different letterform; +33 from this glyph's centre line",
            ],
        },
    },
    "OE": {  # U+0152 Œ
        0: {  # above
            "xy": (480, 850),
            "verdict": "suspect",
            "reasons": [
                'suspect [style-position] anchor sits 33% across the glyph; 51% in the other styles',
            ],
        },
    },
    "oe": {  # U+0153 œ
        0: {  # above
            "xy": (415, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [style-position] anchor sits 33% across the glyph; 52% in the other styles',
            ],
        },
    },
    "uni0181": {  # U+0181 Ɓ
        0: {  # above
            "xy": (327, 805),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 805 is 45 from every reference value although the glyph sits on aspect 'c'",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +167 from that style's; -143 off centre here (+24 there)",
            ],
        },
        2: {  # below
            "xy": (328, -108),
            "verdict": "bad",
            "reasons": [
                "suspect [copy] same anchor as U (U+0055), a different letterform; +44 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -19 from that style's; +44 off centre here (+25 there)",
            ],
        },
    },
    "uni0183": {  # U+0183 ƃ
        2: {  # below
            "xy": (234, -109),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as S (U+0053) and 4 other(s), a different letterform; +20 from this glyph's centre line",
            ],
        },
    },
    "uni0184": {  # U+0184 Ƅ
        0: {  # above
            "xy": (267, 805),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] circumflex overlaps the glyph (1 of 3 marks tested)',
                "bad [reference] y = 805 is 45 from every reference value although the glyph sits on aspect 'c'",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +152 from that style's; -162 off centre here (-10 there)",
            ],
        },
        2: {  # below
            "xy": (268, -108),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as B (U+0042), a different letterform; +24 from this glyph's centre line",
            ],
        },
    },
    "uni018A": {  # U+018A Ɗ
        0: {  # above
            "xy": (306, 805),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 805 is 45 from every reference value although the glyph sits on aspect 'c'",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +165 from that style's; -227 off centre here (-62 there)",
            ],
        },
        2: {  # below
            "xy": (369, -107),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -21 from that style's; +21 off centre here (+0 there)",
            ],
        },
    },
    "uni018C": {  # U+018C ƌ
        0: {  # above
            "xy": (214, 650),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'suspect [centre] anchor x is -182 from the centre line (37% of the width)',
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +121 from that style's; -182 off centre here (-61 there)",
            ],
        },
    },
    "uni0194": {  # U+0194 Ɣ
        0: {  # above
            "xy": (331, 805),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 805 is 45 from every reference value although the glyph sits on aspect 'c'",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +131 from that style's; -109 off centre here (+22 there)",
            ],
        },
    },
    "uni0195": {  # U+0195 ƕ
        0: {  # above
            "xy": (299, 645),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +151 from that style's; -195 off centre here (-44 there)",
            ],
        },
    },
    "uni0199": {  # U+0199 ƙ
        2: {  # below
            "xy": (263, -107),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -24 from that style's; +25 off centre here (+1 there)",
            ],
        },
    },
    "uni019C": {  # U+019C Ɯ
        0: {  # above
            "xy": (431, 801),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 801 is 49 from every reference value although the glyph sits on aspect 'c'",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +164 from that style's; -167 off centre here (-2 there)",
            ],
        },
        2: {  # below
            "xy": (450, -108),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -21 from that style's; +37 off centre here (+16 there)",
            ],
        },
    },
    "uni019E": {  # U+019E ƞ
        0: {  # above
            "xy": (264, 646),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as n (U+006E) and 3 other(s), as is its other anchor, a different letterform; -142 from this glyph's centre line",
                "bad [style-copy] identical to the italic anchor, but this glyph's centre line is +54 from that style's; -142 off centre here (-88 there)",
            ],
        },
        2: {  # below
            "xy": (265, -111),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "bad [aspect] glyph sits on aspect 'd' but y = -111 is the reference of an inner aspect, 117 inside the bottom of the glyph; 0 of 2 tested marks fit there",
            ],
        },
    },
    "uni01A2": {  # U+01A2 Ƣ
        0: {  # above
            "xy": (359, 804),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 804 is 46 from every reference value although the glyph sits on aspect 'c'",
                "suspect [copy] same anchor as Ŋ (U+014A), a different letterform; -256 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +146 from that style's; -256 off centre here (-110 there)",
            ],
        },
    },
    "uni01A3": {  # U+01A3 ƣ
        0: {  # above
            "xy": (356, 646),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +117 from that style's; -133 off centre here (-16 there)",
            ],
        },
    },
    "uni01A4": {  # U+01A4 Ƥ
        2: {  # below
            "xy": (363, -110),
            "verdict": "bad",
            "reasons": [
                "suspect [copy] same anchor as C (U+0043), a different letterform; +116 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -71 from that style's; +116 off centre here (+45 there)",
            ],
        },
    },
    "uni01B4": {  # U+01B4 ƴ
        0: {  # above
            "xy": (270, 644),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +35 from that style's; -82 off centre here (-46 there)",
            ],
        },
    },
    "uni01DD": {  # U+01DD ǝ
        0: {  # above
            "xy": (214, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [centre] anchor x is -148 from the centre line (38% of the width)',
                'suspect [turned] turned form of e (U+0065); anchor x is -128 from the transformed anchor of that letter',
                'suspect [style-position] anchor sits 12% across the glyph; 43% in the other styles',
            ],
        },
    },
    "uni0228": {  # U+0228 Ȩ
        0: {  # above
            "xy": (273, 850),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -172 from the centre line (34% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +174 from that style's; -172 off centre here (+2 there)",
            ],
        },
    },
    "uni0229": {  # U+0229 ȩ
        0: {  # above
            "xy": (224, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -144 from the centre line (37% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +146 from that style's; -144 off centre here (+2 there)",
            ],
        },
    },
    "uni0235": {  # U+0235 ȵ
        0: {  # above
            "xy": (261, 646),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -217 from the centre line (33% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +146 from that style's; -217 off centre here (-72 there)",
            ],
        },
        2: {  # below
            "xy": (262, -111),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
            ],
        },
    },
    "uni0236": {  # U+0236 ȶ
        2: {  # below
            "xy": (163, -109),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "suspect [copy] same anchor as ƭ (U+01AD), a different letterform; -28 from this glyph's centre line",
            ],
        },
    },
    "uni0237": {  # U+0237 ȷ
        0: {  # above
            "xy": (140, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -100 from the centre line (34% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +166 from that style's; -100 off centre here (+66 there)",
                'suspect [style-position] anchor sits 16% across the glyph; 77% in the other styles',
            ],
        },
    },
    "uni0238": {  # U+0238 ȸ
        2: {  # below
            "xy": (348, -109),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as N (U+004E), a different letterform; -22 from this glyph's centre line",
            ],
        },
    },
    "uni0239": {  # U+0239 ȹ
        0: {  # above
            "xy": (377, 646),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +149 from that style's; -146 off centre here (+4 there)",
            ],
        },
    },
    "uni0247": {  # U+0247 ɇ
        0: {  # above
            "xy": (243, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -125 from the centre line (32% of the width)',
                "bad [copy] same anchor as e (U+0065), as is its other anchor, a different letterform; -125 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (234, -110),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] crowded: dot below 29 from the glyph (normally 51), macron below 3 from the glyph (normally 25)',
                "suspect [copy] same anchor as S (U+0053) and 4 other(s), a different letterform; +20 from this glyph's centre line",
            ],
        },
    },
    "uni0249": {  # U+0249 ɉ
        2: {  # below
            "xy": (109, -319),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as J (U+004A), a different letterform; +35 from this glyph's centre line",
            ],
        },
    },
    "uni024D": {  # U+024D ɍ
        0: {  # above
            "xy": (191, 646),
            "verdict": "suspect",
            "reasons": [
                'suspect [centre] anchor x is -162 from the centre line (40% of the width)',
            ],
        },
        2: {  # below
            "xy": (135, -110),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as l (U+006C) and 1 other(s), a different letterform; -64 from this glyph's centre line",
            ],
        },
    },
    "uni0250": {  # U+0250 ɐ
        2: {  # below
            "xy": (229, -114),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -17 from that style's; +30 off centre here (+12 there)",
            ],
        },
    },
    "uni0251": {  # U+0251 ɑ
        0: {  # above
            "xy": (228, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -184 from the centre line (37% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +140 from that style's; -184 off centre here (-44 there)",
            ],
        },
    },
    "uni0252": {  # U+0252 ɒ
        0: {  # above
            "xy": (264, 645),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as n (U+006E) and 3 other(s), a different letterform; -126 from this glyph's centre line",
                'suspect [turned] turned form of ɑ (U+0251); anchor x is -171 from the transformed anchor of that letter',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +143 from that style's; -126 off centre here (+17 there)",
            ],
        },
        2: {  # below
            "xy": (259, -114),
            "verdict": "suspect",
            "reasons": [
                'suspect [turned] turned form of ɑ (U+0251); anchor x is -160 from the transformed anchor of that letter',
            ],
        },
    },
    "uni0253": {  # U+0253 ɓ
        2: {  # below
            "xy": (212, -114),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as ɑ (U+0251) and 7 other(s), a different letterform; -36 from this glyph's centre line",
            ],
        },
    },
    "uni0254": {  # U+0254 ɔ
        0: {  # above
            "xy": (160, 645),
            "verdict": "suspect",
            "reasons": [
                'suspect [centre] anchor x is -175 from the centre line (46% of the width)',
                'suspect [style-position] anchor sits 4% across the glyph; 50% in the other styles',
            ],
        },
    },
    "uni0255": {  # U+0255 ɕ
        2: {  # below
            "xy": (212, -114),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
            ],
        },
    },
    "uni0256": {  # U+0256 ɖ
        0: {  # above
            "xy": (218, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -237 from the centre line (41% of the width)',
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [copy] same anchor as d (U+0064) and 3 other(s), a different letterform; -237 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +141 from that style's; -237 off centre here (-96 there)",
            ],
        },
        2: {  # below
            "xy": (212, -114),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "bad [copy] same anchor as ɑ (U+0251) and 7 other(s), a different letterform; -89 from this glyph's centre line",
            ],
        },
    },
    "uni0257": {  # U+0257 ɗ
        0: {  # above
            "xy": (218, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -248 from the centre line (41% of the width)',
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 1 of 3 tested marks fit there",
                "bad [copy] same anchor as d (U+0064) and 3 other(s), a different letterform; -248 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +144 from that style's; -248 off centre here (-104 there)",
            ],
        },
        2: {  # below
            "xy": (212, -114),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as ɑ (U+0251) and 7 other(s), a different letterform; -100 from this glyph's centre line",
            ],
        },
    },
    "uni0258": {  # U+0258 ɘ
        0: {  # above
            "xy": (204, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -161 from the centre line (40% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +144 from that style's; -161 off centre here (-16 there)",
            ],
        },
    },
    "uni025A": {  # U+025A ɚ
        2: {  # below
            "xy": (212, -114),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as ɑ (U+0251) and 7 other(s), a different letterform; -93 from this glyph's centre line",
            ],
        },
    },
    "uni025B": {  # U+025B ɛ
        0: {  # above
            "xy": (209, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -139 from the centre line (39% of the width)',
                "suspect [copy] same anchor as ą (U+0105), a different letterform; -139 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +146 from that style's; -139 off centre here (+8 there)",
                'suspect [style-position] anchor sits 11% across the glyph; 52% in the other styles',
            ],
        },
        2: {  # below
            "xy": (212, -114),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as ɑ (U+0251) and 7 other(s), a different letterform; +19 from this glyph's centre line",
            ],
        },
    },
    "uni025C": {  # U+025C ɜ
        0: {  # above
            "xy": (194, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -155 from the centre line (44% of the width)',
                'suspect [turned] reversed form of ɛ (U+025B); anchor x is -294 from the transformed anchor of that letter',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +153 from that style's; -155 off centre here (-2 there)",
            ],
        },
    },
    "uni025D": {  # U+025D ɝ
        2: {  # below
            "xy": (212, -114),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as ɑ (U+0251) and 7 other(s), a different letterform; -47 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +25 from that style's; -47 off centre here (-22 there)",
            ],
        },
    },
    "uni0262": {  # U+0262 ɢ
        0: {  # above
            "xy": (265, 645),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +144 from that style's; -137 off centre here (+6 there)",
            ],
        },
    },
    "uni0265": {  # U+0265 ɥ
        0: {  # above
            "xy": (258, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -159 from the centre line (31% of the width)',
                "bad [style-copy] identical to the italic anchor, but this glyph's centre line is +15 from that style's; -159 off centre here (-144 there)",
                'suspect [style-position] anchor sits 19% across the glyph; 35% in the other styles',
            ],
        },
        2: {  # below
            "xy": (219, -129),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "suspect [reference] y = -129 is 19 from the nearest reference value (aspect 'd')",
            ],
        },
    },
    "uni0266": {  # U+0266 ɦ
        0: {  # above
            "xy": (299, 565),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'bad [collision] dot, macron overlap the glyph (2 of 3 marks tested)',
                "bad [reference] y = 565 is 80 from every reference value although the glyph sits on aspect 'a'",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +127 from that style's; -90 off centre here (+36 there)",
            ],
        },
    },
    "uni0267": {  # U+0267 ɧ
        0: {  # above
            "xy": (299, 565),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
                "bad [reference] y = 565 is 80 from every reference value although the glyph sits on aspect 'a'",
            ],
        },
        2: {  # below
            "xy": (240, -114),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
                "bad [aspect] glyph sits on aspect 'd' but y = -114 is the reference of an inner aspect, 115 inside the bottom of the glyph; 0 of 2 tested marks fit there",
                "bad [copy] same anchor as ɦ (U+0266), as is its other anchor, a different letterform; +17 from this glyph's centre line",
            ],
        },
    },
    "uni0268": {  # U+0268 ɨ
        0: {  # above
            "xy": (137, 795),
            "verdict": "bad",
            "reasons": [
                'bad [extent] anchor x is 53 outside the glyph, to the left',
            ],
        },
    },
    "uni0269": {  # U+0269 ɩ
        0: {  # above
            "xy": (123, 645),
            "verdict": "bad",
            "reasons": [
                'bad [extent] anchor x is 33 outside the glyph, to the left',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +132 from that style's; -179 off centre here (-47 there)",
            ],
        },
    },
    "uni026A": {  # U+026A ɪ
        0: {  # above
            "xy": (128, 645),
            "verdict": "bad",
            "reasons": [
                'bad [extent] anchor x is 24 outside the glyph, to the left',
                'suspect [style-position] anchor sits -9% across the glyph; 48% in the other styles',
            ],
        },
    },
    "uni026B": {  # U+026B ɫ
        2: {  # below
            "xy": (146, -114),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +22 from that style's; -20 off centre here (+2 there)",
            ],
        },
    },
    "uni026C": {  # U+026C ɬ
        2: {  # below
            "xy": (218, -120),
            "verdict": "suspect",
            "reasons": [
                "suspect [reference] y = -120 is 10 from the nearest reference value (aspect 'b')",
            ],
        },
    },
    "uni026F": {  # U+026F ɯ
        0: {  # above
            "xy": (407, 645),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +128 from that style's; -112 off centre here (+16 there)",
                'suspect [style-position] anchor sits 35% across the glyph; 53% in the other styles',
            ],
        },
        2: {  # below
            "xy": (410, -114),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -26 from that style's; +45 off centre here (+19 there)",
            ],
        },
    },
    "uni0270": {  # U+0270 ɰ
        2: {  # below
            "xy": (294, -114),
            "verdict": "suspect",
            "reasons": [
                "suspect [aspect] glyph sits on aspect 'd' but y = -114 is the reference of an inner aspect, 112 inside the bottom of the glyph; 2 of 2 tested marks fit there",
            ],
        },
    },
    "uni0271": {  # U+0271 ɱ
        0: {  # above
            "xy": (383, 645),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +133 from that style's; -115 off centre here (+18 there)",
            ],
        },
        2: {  # below
            "xy": (383, -105),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] crowded: dot below 22 from the glyph (normally 51)',
                "suspect [aspect] glyph sits on aspect 'd' but y = -105 is the reference of an inner aspect, 122 inside the bottom of the glyph; 1 of 2 tested marks fit there",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -20 from that style's; +38 off centre here (+18 there)",
            ],
        },
    },
    "uni0272": {  # U+0272 ɲ
        0: {  # above
            "xy": (264, 646),
            "verdict": "bad",
            "reasons": [
                "bad [copy] same anchor as n (U+006E) and 3 other(s), as is its other anchor, a different letterform; -110 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +140 from that style's; -110 off centre here (+30 there)",
            ],
        },
        2: {  # below
            "xy": (265, -111),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "suspect [aspect] glyph sits on aspect 'd' but y = -111 is the reference of an inner aspect, 117 inside the bottom of the glyph; 1 of 2 tested marks fit there",
                "bad [copy] same anchor as n (U+006E) and 2 other(s), as is its other anchor, a different letterform; +45 from this glyph's centre line",
            ],
        },
    },
    "uni0273": {  # U+0273 ɳ
        0: {  # above
            "xy": (263, 645),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +139 from that style's; -172 off centre here (-32 there)",
            ],
        },
        2: {  # below
            "xy": (262, -112),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "bad [aspect] glyph sits on aspect 'd' but y = -112 is the reference of an inner aspect, 117 inside the bottom of the glyph; 0 of 2 tested marks fit there",
                "suspect [copy] same anchor as ȵ (U+0235), a different letterform; -19 from this glyph's centre line",
            ],
        },
    },
    "uni0279": {  # U+0279 ɹ
        2: {  # below
            "xy": (190, -114),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -22 from that style's; +35 off centre here (+13 there)",
            ],
        },
    },
    "uni027C": {  # U+027C ɼ
        0: {  # above
            "xy": (222, 703),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -130 from the centre line (32% of the width)',
                "bad [reference] y = 703 is 58 from every reference value although the glyph sits on aspect 'x'",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +165 from that style's; -130 off centre here (+36 there)",
            ],
        },
    },
    "uni028B": {  # U+028B ʋ
        0: {  # above
            "xy": (259, 645),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +161 from that style's; -137 off centre here (+24 there)",
            ],
        },
    },
    "uni0292": {  # U+0292 ʒ
        0: {  # above
            "xy": (218, 646),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -137 from the centre line (33% of the width)',
                'suspect [precomposed] precomposed glyphs centre marks +151 from this anchor (1 glyph(s) compared)',
                "bad [copy] same anchor as d (U+0064) and 3 other(s), a different letterform; -137 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +139 from that style's; -137 off centre here (+2 there)",
                'suspect [style-position] anchor sits 17% across the glyph; 50% in the other styles',
            ],
        },
    },
    "uni0295": {  # U+0295 ʕ
        2: {  # below
            "xy": (230, -107),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -22 from that style's; +31 off centre here (+9 there)",
            ],
        },
    },
    "uni029E": {  # U+029E ʞ
        0: {  # above
            "xy": (255, 646),
            "verdict": "suspect",
            "reasons": [
                'suspect [centre] anchor x is -171 from the centre line (32% of the width)',
                "suspect [copy] same anchor as u (U+0075) and 1 other(s), a different letterform; -171 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (183, -107),
            "verdict": "suspect",
            "reasons": [
                "suspect [aspect] glyph sits on aspect 'd' but y = -107 is the reference of an inner aspect, 122 inside the bottom of the glyph; 2 of 2 tested marks fit there",
            ],
        },
    },
    "uni02A0": {  # U+02A0 ʠ
        0: {  # above
            "xy": (238, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -242 from the centre line (39% of the width)',
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 0 of 3 tested marks fit there",
                "suspect [copy] same anchor as o (U+006F) and 1 other(s), a different letterform; -242 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +159 from that style's; -242 off centre here (-82 there)",
            ],
        },
    },
    "uni02AE": {  # U+02AE ʮ
        0: {  # above
            "xy": (278, -214),
            "verdict": "bad",
            "reasons": [
                'bad [side] above anchor at y = -214, in the lower half of the glyph or below it',
                'bad [collision] dot, circumflex overlap the glyph (2 of 3 marks tested)',
                'bad [reference] y = -214 is 859 from every reference value',
            ],
        },
        2: {  # below
            "xy": (318, 542),
            "verdict": "bad",
            "reasons": [
                'bad [side] below anchor at y = 542, in the upper half of the glyph or above it',
                'bad [reference] y = 542 is 652 from every reference value',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +134 from that style's; -104 off centre here (+30 there)",
            ],
        },
    },
    "uni02AF": {  # U+02AF ʯ
        0: {  # above
            "xy": (278, -214),
            "verdict": "bad",
            "reasons": [
                'bad [side] above anchor at y = -214, in the lower half of the glyph or below it',
                'suspect [collision] circumflex overlaps the glyph (1 of 3 marks tested)',
                'bad [reference] y = -214 is 859 from every reference value',
                "bad [copy] same anchor as ʮ (U+02AE), as is its other anchor, a different letterform; -22 from this glyph's centre line",
            ],
        },
        2: {  # below
            "xy": (318, 542),
            "verdict": "bad",
            "reasons": [
                'bad [side] below anchor at y = 542, in the upper half of the glyph or above it',
                'bad [reference] y = 542 is 652 from every reference value',
                "bad [copy] same anchor as ʮ (U+02AE), as is its other anchor, a different letterform; -136 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +126 from that style's; -136 off centre here (-10 there)",
            ],
        },
    },
    "beta": {  # U+03B2 β
        2: {  # below
            "xy": (275, -114),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
                "suspect [aspect] glyph sits on aspect 'd' but y = -114 is the reference of an inner aspect, 119 inside the bottom of the glyph; 1 of 2 tested marks fit there",
            ],
        },
    },
    "upsilon": {  # U+03C5 υ
        0: {  # above
            "xy": (259, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -144 from the centre line (31% of the width)',
                'suspect [precomposed] precomposed glyphs centre marks +149 from this anchor (3 glyph(s) compared)',
                "suspect [copy] same anchor as ʋ (U+028B), a different letterform; -144 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +168 from that style's; -144 off centre here (+24 there)",
            ],
        },
    },
    "uni040B": {  # U+040B Ћ
        0: {  # above
            "xy": (300, 802),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -240 from the centre line (32% of the width)',
                "suspect [reference] y = 802 is 48 from both the reference values and the clearance rule (aspect 'a-20')",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +166 from that style's; -240 off centre here (-74 there)",
            ],
        },
        2: {  # below
            "xy": (436, -111),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is -20 from that style's; +82 off centre here (+62 there)",
            ],
        },
    },
    "uni0473": {  # U+0473 ѳ
        0: {  # above
            "xy": (224, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -157 from the centre line (36% of the width)',
                "suspect [copy] same anchor as ȩ (U+0229), a different letterform; -157 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +153 from that style's; -157 off centre here (-4 there)",
                'suspect [style-position] anchor sits 14% across the glyph; 49% in the other styles',
            ],
        },
    },
    "uni0475": {  # U+0475 ѵ
        0: {  # above
            "xy": (268, 646),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +159 from that style's; -156 off centre here (+3 there)",
            ],
        },
    },
    "uni04D5": {  # U+04D5 ӕ
        0: {  # above
            "xy": (341, 645),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +157 from that style's; -159 off centre here (-2 there)",
            ],
        },
    },
    "uni04D9": {  # U+04D9 ә
        0: {  # above
            "xy": (211, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -159 from the centre line (41% of the width)',
                'suspect [precomposed] precomposed glyphs centre marks +46 from this anchor (1 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +138 from that style's; -159 off centre here (-21 there)",
            ],
        },
    },
    "uni04E9": {  # U+04E9 ө
        0: {  # above
            "xy": (236, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -145 from the centre line (33% of the width)',
                'suspect [precomposed] precomposed glyphs centre marks +153 from this anchor (1 glyph(s) compared)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +129 from that style's; -145 off centre here (-16 there)",
                'suspect [style-position] anchor sits 17% across the glyph; 45% in the other styles',
            ],
        },
    },
    "uni05F0": {  # U+05F0 װ
        0: {  # above
            "xy": (243, 573),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
            ],
        },
        2: {  # below
            "xy": (263, 0),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot below, macron below overlap the glyph (2 of 2 marks tested)',
            ],
        },
    },
    "uni05F1": {  # U+05F1 ױ
        0: {  # above
            "xy": (242, 573),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
            ],
        },
    },
    "uni05F2": {  # U+05F2 ײ
        0: {  # above
            "xy": (244, 573),
            "verdict": "bad",
            "reasons": [
                'bad [collision] dot, macron, circumflex overlap the glyph (3 of 3 marks tested)',
            ],
        },
        2: {  # below
            "xy": (240, 0),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as ױ (U+05F1), a different letterform; -20 from this glyph's centre line",
            ],
        },
    },
    "uni1E19": {  # U+1E19 ḙ
        0: {  # above
            "xy": (231, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -137 from the centre line (35% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +146 from that style's; -137 off centre here (+9 there)",
            ],
        },
    },
    "uni1E1B": {  # U+1E1B ḛ
        0: {  # above
            "xy": (231, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -137 from the centre line (35% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +146 from that style's; -137 off centre here (+9 there)",
            ],
        },
    },
    "uni1E2C": {  # U+1E2C Ḭ
        0: {  # above
            "xy": (146, 850),
            "verdict": "bad",
            "reasons": [
                'bad [extent] anchor x is 44 outside the glyph, to the left',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +201 from that style's; -206 off centre here (-5 there)",
            ],
        },
    },
    "uni1E72": {  # U+1E72 Ṳ
        0: {  # above
            "xy": (346, 850),
            "verdict": "bad",
            "reasons": [
                "suspect [copy] same anchor as N (U+004E) and 1 other(s), a different letterform; -169 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +184 from that style's; -169 off centre here (+15 there)",
            ],
        },
    },
    "uni1E73": {  # U+1E73 ṳ
        0: {  # above
            "xy": (255, 645),
            "verdict": "bad",
            "reasons": [
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +141 from that style's; -157 off centre here (-16 there)",
            ],
        },
    },
    "uni1EB9": {  # U+1EB9 ẹ
        0: {  # above
            "xy": (231, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -137 from the centre line (35% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +146 from that style's; -137 off centre here (+9 there)",
            ],
        },
    },
    "uni1ECA": {  # U+1ECA Ị
        0: {  # above
            "xy": (146, 850),
            "verdict": "bad",
            "reasons": [
                'bad [extent] anchor x is 44 outside the glyph, to the left',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +203 from that style's; -206 off centre here (-2 there)",
            ],
        },
    },
    "uni1ECB": {  # U+1ECB ị
        0: {  # above
            "xy": (132, 775),
            "verdict": "bad",
            "reasons": [
                'bad [extent] anchor x is 61 outside the glyph, to the left',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +195 from that style's; -205 off centre here (-10 there)",
            ],
        },
    },
    "uni1ECD": {  # U+1ECD ọ
        0: {  # above
            "xy": (231, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -150 from the centre line (35% of the width)',
                "bad [copy] same anchor as ę (U+0119) and 3 other(s), a different letterform; -150 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +129 from that style's; -150 off centre here (-21 there)",
                'suspect [style-position] anchor sits 15% across the glyph; 48% in the other styles',
            ],
        },
    },
    "uni2184": {  # U+2184 ↄ
        0: {  # above
            "xy": (180, 645),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -165 from the centre line (42% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +144 from that style's; -165 off centre here (-22 there)",
            ],
        },
    },
    "uni2C68": {  # U+2C68 ⱨ
        0: {  # above
            "xy": (299, 645),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "suspect [aspect] glyph sits on aspect 'a' but y = 645 is the reference of an inner aspect, 53 inside the top of the glyph; 1 of 3 tested marks fit there",
                "bad [copy] same anchor as ƕ (U+0195), as is its other anchor, a different letterform; -96 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +132 from that style's; -96 off centre here (+36 there)",
            ],
        },
        2: {  # below
            "xy": (259, -111),
            "verdict": "bad",
            "reasons": [
                'suspect [collision] crowded: macron below 13 from the glyph (normally 25)',
                "bad [copy] same anchor as ƕ (U+0195), as is its other anchor, a different letterform; +18 from this glyph's centre line",
            ],
        },
    },
    "uni2C69": {  # U+2C69 Ⱪ
        0: {  # above
            "xy": (336, 798),
            "verdict": "bad",
            "reasons": [
                "bad [reference] y = 798 is 52 from every reference value although the glyph sits on aspect 'c'",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +174 from that style's; -164 off centre here (+10 there)",
            ],
        },
        2: {  # below
            "xy": (342, -109),
            "verdict": "suspect",
            "reasons": [
                "suspect [copy] same anchor as K (U+004B), a different letterform; +27 from this glyph's centre line",
            ],
        },
    },
    "uni2C6A": {  # U+2C6A ⱪ
        0: {  # above
            "xy": (275, 646),
            "verdict": "bad",
            "reasons": [
                "bad [inside] anchor lies inside the glyph's outline",
                'suspect [collision] macron, circumflex overlap the glyph (2 of 3 marks tested)',
                "bad [aspect] glyph sits on aspect 'a' but y = 646 is the reference of an inner aspect, 52 inside the top of the glyph; 0 of 3 tested marks fit there",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +145 from that style's; -130 off centre here (+16 there)",
            ],
        },
    },
    "uni2C6B": {  # U+2C6B Ⱬ
        0: {  # above
            "xy": (320, 803),
            "verdict": "bad",
            "reasons": [
                "suspect [reference] y = 803 is 47 from both the reference values and the clearance rule (aspect 'c+25')",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +164 from that style's; -166 off centre here (-2 there)",
            ],
        },
    },
    "uni2C6C": {  # U+2C6C ⱬ
        0: {  # above
            "xy": (218, 646),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -126 from the centre line (32% of the width)',
                "bad [copy] same anchor as d (U+0064) and 3 other(s), a different letterform; -126 from this glyph's centre line",
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +138 from that style's; -126 off centre here (+12 there)",
            ],
        },
        2: {  # below
            "xy": (204, -111),
            "verdict": "suspect",
            "reasons": [
                'suspect [collision] macron below overlaps the glyph (1 of 2 marks tested)',
            ],
        },
    },
    "uni2C74": {  # U+2C74 ⱴ
        0: {  # above
            "xy": (252, 646),
            "verdict": "bad",
            "reasons": [
                'suspect [centre] anchor x is -145 from the centre line (31% of the width)',
                "bad [style-copy] identical to the regular anchor, but this glyph's centre line is +142 from that style's; -145 off centre here (-2 there)",
            ],
        },
    },
}
