#!/usr/bin/env python3
"""
run_anchor_audit.py

Audit the designer-set above/below base anchors of the four original fonts
and record every bad or suspect anchor in

    data/fontanchors_audit/{style}.py

and print a test sheet of them to tex/input/anchor_audit.tex, which is
\\input{} from the main LaTeX document.

These files are regenerated on every run; do not edit them. To overrule a
verdict, add an entry to data/fontanchors_audit/overrides.py.

Stage 1 of the patch pipeline (font_patching_deleteanchors.py) deletes the
anchors recorded as bad.
"""

from collections import Counter
from pathlib import Path

from libertinus_analysis.anchor_audit import audit_all_styles, STYLE_KEYS, SIDE_NAMES
from libertinus_analysis.anchor_audit_texformatter import format_all_styles_tex
from libertinus_analysis.config import TEX_INPUT_DIR

OUT_DIR = Path("data/fontanchors_audit")


def format_style(style, entries):
    counts = Counter(e["verdict"] for e in entries.values())
    lines = [
        "# Generated by run_anchor_audit.py. Do not edit: rerunning overwrites this file.",
        "# To overrule a verdict, add an entry to data/fontanchors_audit/overrides.py.",
        "#",
        f"# {style}: {len(entries)} anchors audited; "
        f"{counts['bad']} bad, {counts['suspect']} suspect, {counts['ok']} ok",
        "# anchor class 0 = above, 2 = below",
        "",
        "audit = {",
    ]

    by_glyph = {}
    for e in entries.values():
        if e["verdict"] != "ok":
            by_glyph.setdefault(e["glyph"], []).append(e)

    for glyph, group in sorted(by_glyph.items(), key=lambda kv: kv[1][0]["cp"]):
        cp = group[0]["cp"]
        lines.append(f'    "{glyph}": {{  # U+{cp:04X} {chr(cp)}')
        for e in sorted(group, key=lambda e: e["cls"]):
            lines.append(f'        {e["cls"]}: {{  # {SIDE_NAMES[e["cls"]]}')
            lines.append(f'            "xy": {e["xy"]},')
            lines.append(f'            "verdict": "{e["verdict"]}",')
            lines.append('            "reasons": [')
            for level, key, text in e["findings"]:
                lines.append(f'                {f"{level} [{key}] {text}"!r},')
            lines.append("            ],")
            lines.append("        },")
        lines.append("    },")

    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    all_entries = audit_all_styles()

    for style in STYLE_KEYS:
        entries = all_entries[style]
        out_path = OUT_DIR / f"{style}.py"
        out_path.write_text(format_style(style, entries), encoding="utf-8")

        counts = Counter(e["verdict"] for e in entries.values())
        tests = Counter()
        for e in entries.values():
            for level, key, _ in e["findings"]:
                tests[(level, key)] += 1
        print(f"[{style}] {len(entries)} anchors: {counts['bad']} bad, "
              f"{counts['suspect']} suspect, {counts['ok']} ok -> {out_path}")
        for (level, key), n in sorted(tests.items()):
            print(f"    {level:8} {key:15} {n}")

    tex_path = TEX_INPUT_DIR / "anchor_audit.tex"
    tex_path.write_text(format_all_styles_tex(all_entries), encoding="utf-8")
    print(f"Wrote test sheet to {tex_path}")


if __name__ == "__main__":
    main()
