# anchor_audit_texformatter.py
"""
Format the anchor audit into a LaTeX test sheet.

Used by run_anchor_audit.py to write tex/input/anchor_audit.tex.

Each bad or suspect anchor is shown as a small cell: the codepoint, the
base combined with a few marks through the combining grapheme joiner (so
the marks are positioned by anchor, never replaced by a precomposed glyph),
and short tags naming the tests that flagged it.
"""

from __future__ import annotations

from .anchor_audit import STYLE_KEYS, ABOVE, BELOW, SIDE_NAMES
from .tex_helpers import latex_font_style

STYLE_TITLES = {
    "regular": "Regular",
    "italic": "Italic",
    "semibold": "Semibold",
    "semibold_italic": "Semibold italic",
}

# Marks used to visualize the anchor: the ones the collision test uses
SAMPLE_MARKS = {
    ABOVE: ["0307", "0304", "0302"],   # dot, macron, circumflex
    BELOW: ["0323", "0331"],           # dot below, macron below
}

# Short tags for the test keys, with their legend
TEST_TAGS = {
    "side": ("sid", "anchor on the wrong side of the glyph"),
    "inside": ("in", "anchor inside the outline"),
    "extent": ("ext", "anchor x outside the glyph"),
    "centre": ("ctr", "far from the centre line"),
    "reference": ("ref", "y far from the reference values"),
    "aspect": ("asp", "beside an ascender or descender"),
    "clearance": ("clr", "floats far from the glyph"),
    "collision": ("col", "a mark overlaps or crowds the glyph"),
    "copy": ("cpy", "copied from another glyph"),
    "turned": ("trn", "turned letter not following its source"),
    "style-copy": ("sty", "copied from another style"),
    "precomposed": ("pre", "disagrees with precomposed glyphs"),
    "style-position": ("pos", "position differs between styles"),
}

HEADER = r"""% Generated by run_anchor_audit.py. Do not edit: rerunning overwrites this file.
\providecommand{\AuditItem}[3]{%
  \begin{tabular}[t]{@{}c@{}}{\tiny #1}\\[1pt]{\Large #2}\\[2pt]{\tiny #3}\end{tabular}\hspace{4mm}}
"""


def format_legend() -> str:
    parts = [f"\\textbf{{{tag}}} {text}" for tag, text in TEST_TAGS.values()]
    return "Tags: " + "; ".join(parts) + "."


def format_item(style_key: str, entry: dict) -> str:
    cp = entry["cp"]
    samples = [f'\\char"{cp:04X}\\cgj\\char"{mk}' for mk in SAMPLE_MARKS[entry["cls"]]]
    sample = latex_font_style(style_key, "\\ ".join(samples))

    tags = []
    for _, key, _ in entry["findings"]:
        tag = TEST_TAGS[key][0]
        if tag not in tags:
            tags.append(tag)

    return f"\\AuditItem{{{cp:04X}}}{{{sample}}}{{{' '.join(tags)}}}"


def format_style(style_key: str, entries: dict) -> str:
    lines = [f"\\subsection*{{{STYLE_TITLES[style_key]}}}", ""]

    for verdict in ("bad", "suspect"):
        for cls in (ABOVE, BELOW):
            group = sorted(
                (e for e in entries.values() if e["verdict"] == verdict and e["cls"] == cls),
                key=lambda e: e["cp"],
            )
            if not group:
                continue
            lines.append(f"\\subsubsection*{{{verdict.capitalize()}, {SIDE_NAMES[cls]}-anchor ({len(group)})}}")
            lines.append("")
            lines.append("{\\raggedright\\lineskip=8pt")
            lines.extend(format_item(style_key, e) for e in group)
            lines.append("\\par}")
            lines.append("")

    return "\n".join(lines)


def format_all_styles_tex(all_entries: dict) -> str:
    parts = [HEADER, format_legend(), ""]
    parts.extend(format_style(style, all_entries[style]) for style in STYLE_KEYS)
    return "\n".join(parts)
